# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `byebug` gem.
# Please instead update this file by running `bin/tapioca gem byebug`.


# Main Container for all of Byebug's code
#
#
# Main debugger's container module. Everything is defined under this module
#
#
# Namespace for all of byebug's code
#
#
# Remote debugging functionality.
#
#
# Reopen main module to define the library version
#
# pkg:gem/byebug#lib/byebug/helpers/reflection.rb:3
module Byebug
  include ::Byebug::Helpers::ReflectionHelper
  extend ::Byebug::Helpers::ReflectionHelper
  extend ::Byebug

  # Debugger's display expressions
  #
  # pkg:gem/byebug#lib/byebug/core.rb:31
  def displays; end

  # Debugger's display expressions
  #
  # pkg:gem/byebug#lib/byebug/core.rb:31
  def displays=(_arg0); end

  # Configuration file used for startup commands. Default value is .byebugrc
  #
  # pkg:gem/byebug#lib/byebug/core.rb:25
  def init_file; end

  # Configuration file used for startup commands. Default value is .byebugrc
  #
  # pkg:gem/byebug#lib/byebug/core.rb:25
  def init_file=(_arg0); end

  # Running mode of the debugger. Can be either:
  #
  # * :attached => Attached to a running program through the `byebug` method.
  # * :standalone => Started through `byebug` script.
  # * :off => Ignoring any `byebug` method calls.
  #
  # pkg:gem/byebug#lib/byebug/core.rb:41
  def mode; end

  # Running mode of the debugger. Can be either:
  #
  # * :attached => Attached to a running program through the `byebug` method.
  # * :standalone => Started through `byebug` script.
  # * :off => Ignoring any `byebug` method calls.
  #
  # pkg:gem/byebug#lib/byebug/core.rb:41
  def mode=(_arg0); end

  # Runs normal byebug initialization scripts.
  #
  # Reads and executes the commands from init file (if any) in the current
  # working directory. This is only done if the current directory is different
  # from your home directory. Thus, you can have more than one init file, one
  # generic in your home directory, and another, specific to the program you
  # are debugging, in the directory where you invoke byebug.
  #
  # pkg:gem/byebug#lib/byebug/core.rb:52
  def run_init_script; end

  private

  def add_catchpoint(_arg0); end
  def breakpoints; end
  def catchpoints; end
  def contexts; end
  def current_context; end
  def debug_load(*_arg0); end
  def lock; end
  def post_mortem=(_arg0); end
  def post_mortem?; end
  def raised_exception; end

  # List of folders to load rc files from
  #
  # @note Files will be loaded in the order specified here.
  #
  # pkg:gem/byebug#lib/byebug/core.rb:102
  def rc_dirs; end

  # Runs a initialization script file
  #
  # pkg:gem/byebug#lib/byebug/core.rb:91
  def run_rc_file(rc_file); end

  def start; end
  def started?; end
  def stop; end
  def stoppable?; end
  def thread_context(_arg0); end
  def tracing=(_arg0); end
  def tracing?; end
  def unlock; end
  def verbose=(_arg0); end
  def verbose?; end

  class << self
    # The actual port that the control server is started at
    #
    # pkg:gem/byebug#lib/byebug/remote.rb:25
    def actual_control_port; end

    # The actual port that the server is started at
    #
    # pkg:gem/byebug#lib/byebug/remote.rb:20
    def actual_port; end

    def add_catchpoint(_arg0); end

    # Starts byebug, and stops at the first line of user's code.
    #
    # pkg:gem/byebug#lib/byebug/attacher.rb:10
    def attach; end

    def breakpoints; end
    def catchpoints; end
    def contexts; end
    def current_context; end
    def debug_load(*_arg0); end

    # Saves information about the unhandled exception and gives a byebug
    # prompt back to the user before program termination.
    #
    # pkg:gem/byebug#lib/byebug/core.rb:76
    def handle_post_mortem; end

    # Interrupts the current thread
    #
    # pkg:gem/byebug#lib/byebug/remote.rb:32
    def interrupt; end

    # pkg:gem/byebug#lib/byebug/core.rb:61
    def load_settings; end

    def lock; end

    # pkg:gem/byebug#lib/byebug/remote.rb:59
    def parse_host_and_port(host_port_spec); end

    def post_mortem=(_arg0); end
    def post_mortem?; end
    def raised_exception; end

    # pkg:gem/byebug#lib/byebug/attacher.rb:21
    def spawn(host = T.unsafe(nil), port = T.unsafe(nil)); end

    def start; end

    # Connects to the remote byebug
    #
    # pkg:gem/byebug#lib/byebug/remote.rb:55
    def start_client(host = T.unsafe(nil), port = T.unsafe(nil)); end

    # Starts the remote server control thread
    #
    # pkg:gem/byebug#lib/byebug/remote.rb:48
    def start_control(host = T.unsafe(nil), port = T.unsafe(nil)); end

    # Starts the remote server main thread
    #
    # pkg:gem/byebug#lib/byebug/remote.rb:39
    def start_server(host = T.unsafe(nil), port = T.unsafe(nil)); end

    def started?; end
    def stop; end
    def stoppable?; end
    def thread_context(_arg0); end
    def tracing=(_arg0); end
    def tracing?; end
    def unlock; end
    def verbose=(_arg0); end
    def verbose?; end

    # If in remote mode, wait for the remote connection
    #
    # pkg:gem/byebug#lib/byebug/remote.rb:17
    def wait_connection; end

    # If in remote mode, wait for the remote connection
    #
    # pkg:gem/byebug#lib/byebug/remote.rb:17
    def wait_connection=(_arg0); end

    private

    # pkg:gem/byebug#lib/byebug/remote.rb:66
    def client; end

    # pkg:gem/byebug#lib/byebug/remote.rb:76
    def control; end

    # pkg:gem/byebug#lib/byebug/remote.rb:70
    def server; end
  end
end

# Setting for automatically invoking IRB on every stop.
#
# pkg:gem/byebug#lib/byebug/settings/autoirb.rb:10
class Byebug::AutoirbSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/autoirb.rb:13
  def initialize; end

  # pkg:gem/byebug#lib/byebug/settings/autoirb.rb:17
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/autoirb.rb:25
  def value; end

  # pkg:gem/byebug#lib/byebug/settings/autoirb.rb:21
  def value=(val); end
end

# pkg:gem/byebug#lib/byebug/settings/autoirb.rb:11
Byebug::AutoirbSetting::DEFAULT = T.let(T.unsafe(nil), Integer)

# Setting for automatically listing source code on every stop.
#
# pkg:gem/byebug#lib/byebug/settings/autolist.rb:10
class Byebug::AutolistSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/autolist.rb:13
  def initialize; end

  # pkg:gem/byebug#lib/byebug/settings/autolist.rb:17
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/autolist.rb:25
  def value; end

  # pkg:gem/byebug#lib/byebug/settings/autolist.rb:21
  def value=(val); end
end

# pkg:gem/byebug#lib/byebug/settings/autolist.rb:11
Byebug::AutolistSetting::DEFAULT = T.let(T.unsafe(nil), Integer)

# Setting for automatically invoking Pry on every stop.
#
# pkg:gem/byebug#lib/byebug/settings/autopry.rb:10
class Byebug::AutoprySetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/autopry.rb:13
  def initialize; end

  # pkg:gem/byebug#lib/byebug/settings/autopry.rb:17
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/autopry.rb:25
  def value; end

  # pkg:gem/byebug#lib/byebug/settings/autopry.rb:21
  def value=(val); end
end

# pkg:gem/byebug#lib/byebug/settings/autopry.rb:11
Byebug::AutoprySetting::DEFAULT = T.let(T.unsafe(nil), Integer)

# Setting for automatically saving previously entered commands to history
# when exiting the debugger.
#
# pkg:gem/byebug#lib/byebug/settings/autosave.rb:10
class Byebug::AutosaveSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/autosave.rb:13
  def banner; end
end

# pkg:gem/byebug#lib/byebug/settings/autosave.rb:11
Byebug::AutosaveSetting::DEFAULT = T.let(T.unsafe(nil), TrueClass)

# Command to display short paths in file names.
#
# For example, when displaying source code information.
#
# pkg:gem/byebug#lib/byebug/settings/basename.rb:11
class Byebug::BasenameSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/basename.rb:12
  def banner; end
end

# Implements breakpoint functionality
#
# pkg:gem/byebug#lib/byebug/commands/break.rb:13
class Byebug::BreakCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper
  include ::Byebug::Helpers::FileHelper
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/break.rb:42
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/break.rb:85
  def add_line_breakpoint(file, line); end

  # pkg:gem/byebug#lib/byebug/commands/break.rb:56
  def line_breakpoint(location); end

  # pkg:gem/byebug#lib/byebug/commands/break.rb:67
  def method_breakpoint(location); end

  # pkg:gem/byebug#lib/byebug/commands/break.rb:76
  def target_object(str); end

  # pkg:gem/byebug#lib/byebug/commands/break.rb:106
  def valid_breakpoints_for(path, line); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/break.rb:24
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/break.rb:20
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/break.rb:38
    def short_description; end
  end
end

# Implements breakpoints
#
# pkg:gem/byebug#lib/byebug/breakpoint.rb:7
class Byebug::Breakpoint
  def initialize(_arg0, _arg1, _arg2); end

  def enabled=(_arg0); end
  def enabled?; end
  def expr; end
  def expr=(_arg0); end
  def hit_condition; end
  def hit_condition=(_arg0); end
  def hit_count; end
  def hit_value; end
  def hit_value=(_arg0); end
  def id; end

  # Prints all information associated to the breakpoint
  #
  # pkg:gem/byebug#lib/byebug/breakpoint.rb:88
  def inspect; end

  def pos; end
  def source; end

  class << self
    # Adds a new breakpoint
    #
    # @param [String] file
    # @param [Fixnum] line
    # @param [String] expr
    #
    # pkg:gem/byebug#lib/byebug/breakpoint.rb:29
    def add(file, line, expr = T.unsafe(nil)); end

    # First breakpoint, in order of creation
    #
    # pkg:gem/byebug#lib/byebug/breakpoint.rb:11
    def first; end

    # Last breakpoint, in order of creation
    #
    # pkg:gem/byebug#lib/byebug/breakpoint.rb:18
    def last; end

    # True if there's no breakpoints
    #
    # pkg:gem/byebug#lib/byebug/breakpoint.rb:81
    def none?; end

    # Returns true if a breakpoint could be set in line number +lineno+ in file
    # name +filename.
    #
    # pkg:gem/byebug#lib/byebug/breakpoint.rb:74
    def potential_line?(filename, lineno); end

    # Returns an array of line numbers in file named +filename+ where
    # breakpoints could be set. The list will contain an entry for each
    # distinct line event call so it is possible (and possibly useful) for a
    # line number appear more than once.
    #
    # @param filename [String] File name to inspect for possible breakpoints
    #
    # pkg:gem/byebug#lib/byebug/breakpoint.rb:52
    def potential_lines(filename); end

    # Removes a breakpoint
    #
    # @param id [integer] breakpoint number
    #
    # pkg:gem/byebug#lib/byebug/breakpoint.rb:40
    def remove(id); end

    private

    # pkg:gem/byebug#lib/byebug/breakpoint.rb:59
    def potential_lines_with_trace_points(iseq, lines); end
  end
end

# Setting to customize the verbosity level for stack frames.
#
# pkg:gem/byebug#lib/byebug/settings/callstyle.rb:9
class Byebug::CallstyleSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/callstyle.rb:12
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/callstyle.rb:16
  def to_s; end
end

# pkg:gem/byebug#lib/byebug/settings/callstyle.rb:10
Byebug::CallstyleSetting::DEFAULT = T.let(T.unsafe(nil), String)

# Implements exception catching.
#
# Enables the user to catch unhandled assertion when they happen.
#
# pkg:gem/byebug#lib/byebug/commands/catch.rb:12
class Byebug::CatchCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper

  # pkg:gem/byebug#lib/byebug/commands/catch.rb:38
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/catch.rb:57
  def add(exception); end

  # pkg:gem/byebug#lib/byebug/commands/catch.rb:64
  def clear; end

  # pkg:gem/byebug#lib/byebug/commands/catch.rb:68
  def info; end

  # pkg:gem/byebug#lib/byebug/commands/catch.rb:50
  def remove(exception); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/catch.rb:21
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/catch.rb:17
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/catch.rb:34
    def short_description; end
  end
end

# Parent class of all byebug commands.
#
# Subclass it and name the subclass ending with the word Command to implement
# your own custom command.
#
# @example Define a custom command
#
# class MyCustomCommand < Command
#   def self.regexp
#     /custom_regexp/
#   end
#
#   def self.description
#     "Custom long desc"
#   end
#
#   def.short_description
#     "Custom short desc"
#   end
#
#   def execute
#     # My command's implementation
#   end
# end
#
# pkg:gem/byebug#lib/byebug/command.rb:33
class Byebug::Command
  extend ::Forwardable
  extend ::Byebug::Helpers::StringHelper

  # pkg:gem/byebug#lib/byebug/command.rb:38
  def initialize(processor, input = T.unsafe(nil)); end

  # pkg:gem/byebug#lib/byebug/command.rb:51
  def arguments; end

  # pkg:gem/byebug#lib/byebug/command.rb:61
  def confirm(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/command.rb:43
  def context; end

  # pkg:gem/byebug#lib/byebug/command.rb:61
  def errmsg(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/command.rb:47
  def frame; end

  # pkg:gem/byebug#lib/byebug/command.rb:55
  def help(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/command.rb:55
  def match(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/command.rb:57
  def pr(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/command.rb:58
  def prc(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/command.rb:61
  def print(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/command.rb:36
  def processor; end

  # pkg:gem/byebug#lib/byebug/command.rb:59
  def prv(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/command.rb:61
  def puts(*args, **_arg1, &block); end

  class << self
    # Special methods to allow command filtering in processors
    #
    # pkg:gem/byebug#lib/byebug/command.rb:69
    def allow_in_control; end

    # Special methods to allow command filtering in processors
    #
    # pkg:gem/byebug#lib/byebug/command.rb:69
    def allow_in_control=(_arg0); end

    # Special methods to allow command filtering in processors
    #
    # pkg:gem/byebug#lib/byebug/command.rb:69
    def allow_in_post_mortem; end

    # Special methods to allow command filtering in processors
    #
    # pkg:gem/byebug#lib/byebug/command.rb:69
    def allow_in_post_mortem=(_arg0); end

    # pkg:gem/byebug#lib/byebug/command.rb:73
    def always_run; end

    # pkg:gem/byebug#lib/byebug/command.rb:71
    def always_run=(_arg0); end

    # pkg:gem/byebug#lib/byebug/command.rb:88
    def columnize(width); end

    # Default help text for a command.
    #
    # pkg:gem/byebug#lib/byebug/command.rb:99
    def help; end

    # Command's regexp match against an input
    #
    # pkg:gem/byebug#lib/byebug/command.rb:106
    def match(input); end

    # Name of the command, as executed by the user.
    #
    # pkg:gem/byebug#lib/byebug/command.rb:80
    def to_s; end
  end
end

# Holds an array of subcommands for a command
#
# pkg:gem/byebug#lib/byebug/command_list.rb:9
class Byebug::CommandList
  include ::Enumerable

  # pkg:gem/byebug#lib/byebug/command_list.rb:12
  def initialize(commands); end

  # pkg:gem/byebug#lib/byebug/command_list.rb:20
  def each; end

  # pkg:gem/byebug#lib/byebug/command_list.rb:16
  def match(input); end

  # pkg:gem/byebug#lib/byebug/command_list.rb:24
  def to_s; end

  private

  # pkg:gem/byebug#lib/byebug/command_list.rb:30
  def width; end
end

# Custom exception exception to signal "command not found" errors
#
# pkg:gem/byebug#lib/byebug/errors.rb:7
class Byebug::CommandNotFound < ::NoMethodError
  # pkg:gem/byebug#lib/byebug/errors.rb:8
  def initialize(input, parent = T.unsafe(nil)); end

  private

  # pkg:gem/byebug#lib/byebug/errors.rb:25
  def build_cmd(*args); end

  # pkg:gem/byebug#lib/byebug/errors.rb:21
  def help; end

  # pkg:gem/byebug#lib/byebug/errors.rb:17
  def name; end
end

# Processes commands in regular mode.
#
# You can override this class to create your own command processor that, for
# example, whitelists only certain commands to be executed.
#
# @see PostMortemProcessor for a example
#
# pkg:gem/byebug#lib/byebug/processors/command_processor.rb:17
class Byebug::CommandProcessor
  include ::Byebug::Helpers::EvalHelper
  extend ::Forwardable

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:23
  def initialize(context, interface = T.unsafe(nil)); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:64
  def at_breakpoint(brkpt); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:70
  def at_catchpoint(exception); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:80
  def at_end; end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:54
  def at_line; end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:74
  def at_return(return_value); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:58
  def at_tracing; end

  # Available commands
  #
  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:50
  def command_list; end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:45
  def commands(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:43
  def confirm(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:21
  def context; end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:43
  def errmsg(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:37
  def frame(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:21
  def interface; end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:39
  def pr(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:40
  def prc(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:20
  def prev_line; end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:20
  def prev_line=(_arg0); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:31
  def printer; end

  # Let the execution continue
  #
  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:87
  def proceed!; end

  # Handle byebug commands.
  #
  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:94
  def process_commands; end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:41
  def prv(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:43
  def puts(*args, **_arg1, &block); end

  protected

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:119
  def after_repl; end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:111
  def before_repl; end

  # Prompt shown before reading a command.
  #
  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:107
  def prompt; end

  # Main byebug's REPL
  #
  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:126
  def repl; end

  private

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:139
  def auto_cmds_for(run_level); end

  # Run permanent commands.
  #
  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:146
  def run_auto_cmds(run_level); end

  # Executes the received input
  #
  # Instantiates a command matching the input and runs it. If a matching
  # command is not found, it evaluates the unknown input.
  #
  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:158
  def run_cmd(input); end

  # pkg:gem/byebug#lib/byebug/processors/command_processor.rb:167
  def safely; end
end

# Implements conditions on breakpoints.
#
# Adds the ability to stop on breakpoints only under certain conditions.
#
# pkg:gem/byebug#lib/byebug/commands/condition.rb:12
class Byebug::ConditionCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/condition.rb:38
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/condition.rb:21
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/condition.rb:17
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/condition.rb:34
    def short_description; end
  end
end

# Maintains context information for the debugger and it's the main
# communication point between the library and the C-extension through the
# at_breakpoint, at_catchpoint, at_tracing, at_line and at_return callbacks
#
# pkg:gem/byebug#lib/byebug/context.rb:14
class Byebug::Context
  include ::Byebug::Helpers::FileHelper
  extend ::Byebug::Helpers::PathHelper
  extend ::Forwardable

  # Breakpoint handler
  #
  # pkg:gem/byebug#lib/byebug/context.rb:113
  def at_breakpoint(breakpoint); end

  # Catchpoint handler
  #
  # pkg:gem/byebug#lib/byebug/context.rb:120
  def at_catchpoint(exception); end

  # End of class definition handler
  #
  # pkg:gem/byebug#lib/byebug/context.rb:136
  def at_end; end

  # Line handler
  #
  # pkg:gem/byebug#lib/byebug/context.rb:94
  def at_line; end

  # Return handler
  #
  # pkg:gem/byebug#lib/byebug/context.rb:127
  def at_return(return_value); end

  # Tracing handler
  #
  # pkg:gem/byebug#lib/byebug/context.rb:104
  def at_tracing; end

  def backtrace; end
  def dead?; end

  # pkg:gem/byebug#lib/byebug/context.rb:58
  def file(*args, **_arg1, &block); end

  # Reader for the current frame
  #
  # pkg:gem/byebug#lib/byebug/context.rb:46
  def frame; end

  # Writer for the current frame
  #
  # pkg:gem/byebug#lib/byebug/context.rb:53
  def frame=(pos); end

  def frame_binding(*_arg0); end
  def frame_class(*_arg0); end
  def frame_file(*_arg0); end
  def frame_line(*_arg0); end
  def frame_method(*_arg0); end
  def frame_self(*_arg0); end

  # Current file, line and source code information
  #
  # pkg:gem/byebug#lib/byebug/context.rb:70
  def full_location; end

  def ignored?; end

  # pkg:gem/byebug#lib/byebug/context.rb:87
  def interrupt; end

  # pkg:gem/byebug#lib/byebug/context.rb:58
  def line(*args, **_arg1, &block); end

  # Current file & line information
  #
  # pkg:gem/byebug#lib/byebug/context.rb:63
  def location; end

  def resume; end

  # Context's stack size
  #
  # pkg:gem/byebug#lib/byebug/context.rb:79
  def stack_size; end

  def step_into(*_arg0); end
  def step_out(*_arg0); end
  def step_over(*_arg0); end
  def stop_reason; end
  def suspend; end
  def suspended?; end
  def switch; end
  def thnum; end
  def thread; end
  def tracing; end
  def tracing=(_arg0); end

  private

  # Tells whether a file is ignored by the debugger.
  #
  # @param path [String] filename to be checked.
  #
  # pkg:gem/byebug#lib/byebug/context.rb:153
  def ignored_file?(path); end

  # pkg:gem/byebug#lib/byebug/context.rb:144
  def processor; end

  class << self
    # List of files byebug will ignore while debugging
    #
    # pkg:gem/byebug#lib/byebug/context.rb:25
    def ignored_files; end

    # List of files byebug will ignore while debugging
    #
    # pkg:gem/byebug#lib/byebug/context.rb:20
    def ignored_files=(_arg0); end

    # pkg:gem/byebug#lib/byebug/context.rb:32
    def interface; end

    # pkg:gem/byebug#lib/byebug/context.rb:30
    def interface=(_arg0); end

    # pkg:gem/byebug#lib/byebug/context.rb:38
    def processor; end

    # pkg:gem/byebug#lib/byebug/context.rb:36
    def processor=(_arg0); end
  end
end

# Implements the continue command.
#
# Allows the user to continue execution until the next stopping point, a
# specific line number or until program termination.
#
# pkg:gem/byebug#lib/byebug/commands/continue.rb:13
class Byebug::ContinueCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/continue.rb:37
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/continue.rb:64
  def modifier; end

  # pkg:gem/byebug#lib/byebug/commands/continue.rb:60
  def unconditionally?; end

  # pkg:gem/byebug#lib/byebug/commands/continue.rb:56
  def until_line?; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/continue.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/continue.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/continue.rb:33
    def short_description; end
  end
end

# Processes commands when there's not program running
#
# pkg:gem/byebug#lib/byebug/processors/control_processor.rb:9
class Byebug::ControlProcessor < ::Byebug::CommandProcessor
  # Available commands
  #
  # pkg:gem/byebug#lib/byebug/processors/control_processor.rb:13
  def commands; end

  # Prompt shown before reading a command.
  #
  # pkg:gem/byebug#lib/byebug/processors/control_processor.rb:20
  def prompt; end
end

# Spawns a subdebugger and evaluates the given expression
#
# pkg:gem/byebug#lib/byebug/commands/debug.rb:10
class Byebug::DebugCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper

  # pkg:gem/byebug#lib/byebug/commands/debug.rb:32
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/debug.rb:17
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/debug.rb:13
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/debug.rb:28
    def short_description; end
  end
end

class Byebug::DebugThread < ::Thread
  class << self
    def inherited; end
  end
end

# Implements breakpoint deletion.
#
# pkg:gem/byebug#lib/byebug/commands/delete.rb:10
class Byebug::DeleteCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/delete.rb:35
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/delete.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/delete.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/delete.rb:31
    def short_description; end
  end
end

# Disabling custom display expressions or breakpoints.
#
#
# Reopens the +disable+ command to define the +breakpoints+ subcommand
#
#
# Reopens the +disable+ command to define the +display+ subcommand
#
# pkg:gem/byebug#lib/byebug/commands/disable/breakpoints.rb:9
class Byebug::DisableCommand < ::Byebug::Command
  include ::Byebug::Subcommands
  extend ::Byebug::Helpers::ReflectionHelper
  extend ::Byebug::Subcommands::ClassMethods

  class << self
    # pkg:gem/byebug#lib/byebug/commands/disable.rb:21
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/disable.rb:17
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/disable.rb:29
    def short_description; end
  end
end

# Disables all or specific breakpoints
#
# pkg:gem/byebug#lib/byebug/commands/disable/breakpoints.rb:13
class Byebug::DisableCommand::BreakpointsCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper
  include ::Byebug::Helpers::ToggleHelper

  # pkg:gem/byebug#lib/byebug/commands/disable/breakpoints.rb:37
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/disable/breakpoints.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/disable/breakpoints.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/disable/breakpoints.rb:33
    def short_description; end
  end
end

# Enables all or specific displays
#
# pkg:gem/byebug#lib/byebug/commands/disable/display.rb:13
class Byebug::DisableCommand::DisplayCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper
  include ::Byebug::Helpers::ToggleHelper

  # pkg:gem/byebug#lib/byebug/commands/disable/display.rb:38
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/disable/display.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/disable/display.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/disable/display.rb:34
    def short_description; end
  end
end

# Custom expressions to be displayed every time the debugger stops.
#
# pkg:gem/byebug#lib/byebug/commands/display.rb:10
class Byebug::DisplayCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper

  # pkg:gem/byebug#lib/byebug/commands/display.rb:35
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/display.rb:44
  def display_expression(exp); end

  # pkg:gem/byebug#lib/byebug/commands/display.rb:60
  def eval_expr(expression); end

  # pkg:gem/byebug#lib/byebug/commands/display.rb:50
  def print_display_expressions; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/display.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/display.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/display.rb:31
    def short_description; end
  end
end

# Move the current frame down in the backtrace.
#
# pkg:gem/byebug#lib/byebug/commands/down.rb:12
class Byebug::DownCommand < ::Byebug::Command
  include ::Byebug::Helpers::FrameHelper
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/down.rb:36
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/down.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/down.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/down.rb:32
    def short_description; end
  end
end

# Edit a file from byebug's prompt.
#
# pkg:gem/byebug#lib/byebug/commands/edit.rb:9
class Byebug::EditCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/edit.rb:33
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/edit.rb:65
  def edit_error(type, file); end

  # pkg:gem/byebug#lib/byebug/commands/edit.rb:61
  def editor; end

  # pkg:gem/byebug#lib/byebug/commands/edit.rb:45
  def location(matched); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/edit.rb:17
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/edit.rb:13
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/edit.rb:29
    def short_description; end
  end
end

# Enabling custom display expressions or breakpoints.
#
#
# Reopens the +enable+ command to define the +breakpoints+ subcommand
#
#
# Reopens the +enable+ command to define the +display+ subcommand
#
# pkg:gem/byebug#lib/byebug/commands/enable/breakpoints.rb:9
class Byebug::EnableCommand < ::Byebug::Command
  include ::Byebug::Subcommands
  extend ::Byebug::Helpers::ReflectionHelper
  extend ::Byebug::Subcommands::ClassMethods

  class << self
    # pkg:gem/byebug#lib/byebug/commands/enable.rb:21
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/enable.rb:17
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/enable.rb:29
    def short_description; end
  end
end

# Enables all or specific breakpoints
#
# pkg:gem/byebug#lib/byebug/commands/enable/breakpoints.rb:13
class Byebug::EnableCommand::BreakpointsCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper
  include ::Byebug::Helpers::ToggleHelper

  # pkg:gem/byebug#lib/byebug/commands/enable/breakpoints.rb:37
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/enable/breakpoints.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/enable/breakpoints.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/enable/breakpoints.rb:33
    def short_description; end
  end
end

# Enables all or specific displays
#
# pkg:gem/byebug#lib/byebug/commands/enable/display.rb:13
class Byebug::EnableCommand::DisplayCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper
  include ::Byebug::Helpers::ToggleHelper

  # pkg:gem/byebug#lib/byebug/commands/enable/display.rb:38
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/enable/display.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/enable/display.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/enable/display.rb:34
    def short_description; end
  end
end

# Implements the finish functionality.
#
# Allows the user to continue execution until certain frames are finished.
#
# pkg:gem/byebug#lib/byebug/commands/finish.rb:12
class Byebug::FinishCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/finish.rb:37
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/finish.rb:53
  def max_frames; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/finish.rb:21
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/finish.rb:17
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/finish.rb:33
    def short_description; end
  end
end

# Represents a frame in the stack trace
#
# pkg:gem/byebug#lib/byebug/frame.rb:9
class Byebug::Frame
  include ::Byebug::Helpers::FileHelper

  # pkg:gem/byebug#lib/byebug/frame.rb:14
  def initialize(context, pos); end

  # pkg:gem/byebug#lib/byebug/frame.rb:31
  def _binding; end

  # pkg:gem/byebug#lib/byebug/frame.rb:35
  def _class; end

  # pkg:gem/byebug#lib/byebug/frame.rb:39
  def _method; end

  # pkg:gem/byebug#lib/byebug/frame.rb:27
  def _self; end

  # Gets current method arguments for the frame.
  #
  # pkg:gem/byebug#lib/byebug/frame.rb:62
  def args; end

  # Checks whether the frame is a c-frame
  #
  # pkg:gem/byebug#lib/byebug/frame.rb:141
  def c_frame?; end

  # pkg:gem/byebug#lib/byebug/frame.rb:43
  def current?; end

  # Builds a string containing all available args in the frame number, in a
  # verbose or non verbose way according to the value of the +callstyle+
  # setting
  #
  # pkg:gem/byebug#lib/byebug/frame.rb:89
  def deco_args; end

  # pkg:gem/byebug#lib/byebug/frame.rb:76
  def deco_block; end

  # Builds a formatted string containing information about current method call
  #
  # pkg:gem/byebug#lib/byebug/frame.rb:106
  def deco_call; end

  # Returns the current class in the frame or an empty string if the current
  # +callstyle+ setting is 'short'
  #
  # pkg:gem/byebug#lib/byebug/frame.rb:72
  def deco_class; end

  # Formatted filename in frame
  #
  # pkg:gem/byebug#lib/byebug/frame.rb:113
  def deco_file; end

  # pkg:gem/byebug#lib/byebug/frame.rb:80
  def deco_method; end

  # Properly formatted frame number of frame
  #
  # pkg:gem/byebug#lib/byebug/frame.rb:120
  def deco_pos; end

  # pkg:gem/byebug#lib/byebug/frame.rb:19
  def file; end

  # pkg:gem/byebug#lib/byebug/frame.rb:23
  def line; end

  # Gets local variables for the frame.
  #
  # pkg:gem/byebug#lib/byebug/frame.rb:50
  def locals; end

  # Formatted mark for the frame.
  #
  # --> marks the current frame
  # ͱ-- marks c-frames
  #     marks regular frames
  #
  # pkg:gem/byebug#lib/byebug/frame.rb:131
  def mark; end

  # pkg:gem/byebug#lib/byebug/frame.rb:12
  def pos; end

  # pkg:gem/byebug#lib/byebug/frame.rb:145
  def to_hash; end

  private

  # pkg:gem/byebug#lib/byebug/frame.rb:158
  def c_args; end

  # pkg:gem/byebug#lib/byebug/frame.rb:178
  def prefix_and_default(arg_type); end

  # pkg:gem/byebug#lib/byebug/frame.rb:164
  def ruby_args; end

  # pkg:gem/byebug#lib/byebug/frame.rb:174
  def use_short_style?(arg); end
end

# Move to specific frames in the backtrace.
#
# pkg:gem/byebug#lib/byebug/commands/frame.rb:12
class Byebug::FrameCommand < ::Byebug::Command
  include ::Byebug::Helpers::FrameHelper
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/frame.rb:46
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/frame.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/frame.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/frame.rb:42
    def short_description; end
  end
end

# Setting to display full paths in backtraces.
#
# pkg:gem/byebug#lib/byebug/settings/fullpath.rb:9
class Byebug::FullpathSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/fullpath.rb:12
  def banner; end
end

# pkg:gem/byebug#lib/byebug/settings/fullpath.rb:10
Byebug::FullpathSetting::DEFAULT = T.let(T.unsafe(nil), TrueClass)

# Ask for help from byebug's prompt.
#
# pkg:gem/byebug#lib/byebug/commands/help.rb:10
class Byebug::HelpCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/help.rb:34
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/help.rb:54
  def command; end

  # pkg:gem/byebug#lib/byebug/commands/help.rb:48
  def help_for(input, cmd); end

  # pkg:gem/byebug#lib/byebug/commands/help.rb:44
  def help_for_all; end

  # pkg:gem/byebug#lib/byebug/commands/help.rb:58
  def subcommand; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/help.rb:18
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/help.rb:14
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/help.rb:30
    def short_description; end
  end
end

# pkg:gem/byebug#lib/byebug/helpers/reflection.rb:4
module Byebug::Helpers; end

# Utilities for interaction with executables
#
# pkg:gem/byebug#lib/byebug/helpers/bin.rb:8
module Byebug::Helpers::BinHelper
  # pkg:gem/byebug#lib/byebug/helpers/bin.rb:38
  def executable_file_extensions; end

  # pkg:gem/byebug#lib/byebug/helpers/bin.rb:24
  def find_executable(path, cmd); end

  # pkg:gem/byebug#lib/byebug/helpers/bin.rb:42
  def real_executable?(file); end

  # pkg:gem/byebug#lib/byebug/helpers/bin.rb:34
  def search_paths; end

  # Cross-platform way of finding an executable in the $PATH.
  # Adapted from: https://gist.github.com/steakknife/88b6c3837a5e90a08296
  #
  # pkg:gem/byebug#lib/byebug/helpers/bin.rb:13
  def which(cmd); end
end

# Utilities to assist evaluation of code strings
#
# pkg:gem/byebug#lib/byebug/helpers/eval.rb:8
module Byebug::Helpers::EvalHelper
  # Evaluates a string containing Ruby code in a specific binding,
  # handling the errors at an error level.
  #
  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:46
  def error_eval(str, binding = T.unsafe(nil)); end

  # Evaluates an +expression+ that might use or defer execution to threads
  # other than the current one.
  #
  # @note This is necessary because when in byebug's prompt, every thread is
  # "frozen" so that nothing gets run. So we need to unlock threads prior
  # to evaluation or we will run into a deadlock.
  #
  # @param expression [String] Expression to evaluate
  #
  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:30
  def multiple_thread_eval(expression); end

  # Evaluates an +expression+ in a separate thread.
  #
  # @param expression [String] Expression to evaluate
  #
  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:14
  def separate_thread_eval(expression); end

  # Evaluates a string containing Ruby code in a specific binding,
  # returning nil if an error happens.
  #
  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:38
  def silent_eval(str, binding = T.unsafe(nil)); end

  # Evaluates a string containing Ruby code in a specific binding,
  # handling the errors at a warning level.
  #
  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:54
  def warning_eval(str, binding = T.unsafe(nil)); end

  private

  # Run block temporarily ignoring all TracePoint events.
  #
  # Used to evaluate stuff within Byebug's prompt. Otherwise, any code
  # creating new threads won't be properly evaluated because new threads
  # will get blocked by byebug's main thread.
  #
  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:91
  def allowing_other_threads(&block); end

  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:72
  def error_msg(exception); end

  # Runs the given block in a new thread, waits for it to finish and
  # returns the new thread's result.
  #
  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:103
  def in_new_thread; end

  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:66
  def msg(exception); end

  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:60
  def safe_eval(str, binding); end

  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:111
  def safe_inspect(var); end

  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:117
  def safe_to_s(var); end

  # pkg:gem/byebug#lib/byebug/helpers/eval.rb:80
  def warning_msg(exception); end
end

# Utilities for interaction with files
#
# pkg:gem/byebug#lib/byebug/helpers/file.rb:8
module Byebug::Helpers::FileHelper
  # Reads line number +lineno+ from file named +filename+
  #
  # pkg:gem/byebug#lib/byebug/helpers/file.rb:19
  def get_line(filename, lineno); end

  # Reads lines of source file +filename+ into an array
  #
  # pkg:gem/byebug#lib/byebug/helpers/file.rb:12
  def get_lines(filename); end

  # Returns the number of lines in file +filename+ in a portable,
  # one-line-at-a-time way.
  #
  # pkg:gem/byebug#lib/byebug/helpers/file.rb:30
  def n_lines(filename); end

  # Regularize file name.
  #
  # pkg:gem/byebug#lib/byebug/helpers/file.rb:37
  def normalize(filename); end

  # A short version of a long path
  #
  # pkg:gem/byebug#lib/byebug/helpers/file.rb:48
  def shortpath(fullpath); end

  # True for special files like -e, false otherwise
  #
  # pkg:gem/byebug#lib/byebug/helpers/file.rb:58
  def virtual_file?(name); end
end

# Utilities to assist frame navigation
#
# pkg:gem/byebug#lib/byebug/helpers/frame.rb:8
module Byebug::Helpers::FrameHelper
  # pkg:gem/byebug#lib/byebug/helpers/frame.rb:16
  def jump_frames(steps); end

  # pkg:gem/byebug#lib/byebug/helpers/frame.rb:9
  def switch_to_frame(frame); end

  private

  # pkg:gem/byebug#lib/byebug/helpers/frame.rb:22
  def adjust_frame(new_frame); end

  # @param step [Integer] A positive or negative integer
  #
  # @return [Integer] +1 if step is positive / -1 if negative
  #
  # pkg:gem/byebug#lib/byebug/helpers/frame.rb:60
  def direction(step); end

  # pkg:gem/byebug#lib/byebug/helpers/frame.rb:51
  def frame_err(msg); end

  # Convert a possibly negative index to a positive index from the start
  # of the callstack. -1 is the last position in the stack and so on.
  #
  # @param i [Integer] Integer to be converted in a proper positive index.
  #
  # pkg:gem/byebug#lib/byebug/helpers/frame.rb:70
  def index_from_start(index); end

  # pkg:gem/byebug#lib/byebug/helpers/frame.rb:30
  def navigate_to_frame(jump_no); end

  # pkg:gem/byebug#lib/byebug/helpers/frame.rb:47
  def out_of_bounds?(pos); end
end

# Utilities to assist command parsing
#
# pkg:gem/byebug#lib/byebug/helpers/parse.rb:10
module Byebug::Helpers::ParseHelper
  # Parses +str+ of command +cmd+ as an integer between +min+ and +max+.
  #
  # If either +min+ or +max+ is nil, that value has no bound.
  #
  # @todo Remove the `cmd` parameter. It has nothing to do with the method's
  # purpose.
  #
  # pkg:gem/byebug#lib/byebug/helpers/parse.rb:19
  def get_int(str, cmd, min = T.unsafe(nil), max = T.unsafe(nil)); end

  # @return +str+ as an integer or 1 if +str+ is empty.
  #
  # pkg:gem/byebug#lib/byebug/helpers/parse.rb:58
  def parse_steps(str, cmd); end

  # @return true if code is syntactically correct for Ruby, false otherwise
  #
  # pkg:gem/byebug#lib/byebug/helpers/parse.rb:37
  def syntax_valid?(code); end

  private

  # Temporarily disable output to $stderr
  #
  # pkg:gem/byebug#lib/byebug/helpers/parse.rb:72
  def without_stderr; end
end

# Utilities for managing gem paths
#
# pkg:gem/byebug#lib/byebug/helpers/path.rb:8
module Byebug::Helpers::PathHelper
  # pkg:gem/byebug#lib/byebug/helpers/path.rb:29
  def all_files; end

  # pkg:gem/byebug#lib/byebug/helpers/path.rb:9
  def bin_file; end

  # pkg:gem/byebug#lib/byebug/helpers/path.rb:25
  def gem_files; end

  # pkg:gem/byebug#lib/byebug/helpers/path.rb:17
  def lib_files; end

  # pkg:gem/byebug#lib/byebug/helpers/path.rb:13
  def root_path; end

  # pkg:gem/byebug#lib/byebug/helpers/path.rb:21
  def test_files; end

  private

  # pkg:gem/byebug#lib/byebug/helpers/path.rb:35
  def glob_for(dir); end
end

# Reflection utility
#
# pkg:gem/byebug#lib/byebug/helpers/reflection.rb:8
module Byebug::Helpers::ReflectionHelper
  # List of "command" classes in the including module
  #
  # pkg:gem/byebug#lib/byebug/helpers/reflection.rb:12
  def commands; end
end

# Utilities for interaction with strings
#
# pkg:gem/byebug#lib/byebug/helpers/string.rb:8
module Byebug::Helpers::StringHelper
  # Converts +str+ from an_underscored-or-dasherized_string to
  # ACamelizedString.
  #
  # pkg:gem/byebug#lib/byebug/helpers/string.rb:13
  def camelize(str); end

  # Removes a number of leading whitespace for each input line.
  #
  # pkg:gem/byebug#lib/byebug/helpers/string.rb:28
  def deindent(str, leading_spaces: T.unsafe(nil)); end

  # Improves indentation and spacing in +str+ for readability in Byebug's
  # command prompt.
  #
  # pkg:gem/byebug#lib/byebug/helpers/string.rb:21
  def prettify(str); end
end

# Utilities for thread subcommands
#
# pkg:gem/byebug#lib/byebug/helpers/thread.rb:8
module Byebug::Helpers::ThreadHelper
  # pkg:gem/byebug#lib/byebug/helpers/thread.rb:30
  def context_from_thread(thnum); end

  # pkg:gem/byebug#lib/byebug/helpers/thread.rb:26
  def current_thread?(ctx); end

  # pkg:gem/byebug#lib/byebug/helpers/thread.rb:9
  def display_context(ctx); end

  # pkg:gem/byebug#lib/byebug/helpers/thread.rb:13
  def thread_arguments(ctx); end

  private

  # pkg:gem/byebug#lib/byebug/helpers/thread.rb:62
  def debug_flag(ctx); end

  # @todo Check whether it is Byebug.current_context or context
  #
  # pkg:gem/byebug#lib/byebug/helpers/thread.rb:47
  def location(ctx); end

  # pkg:gem/byebug#lib/byebug/helpers/thread.rb:56
  def status_flag(ctx); end
end

# Utilities to assist breakpoint/display enabling/disabling.
#
# pkg:gem/byebug#lib/byebug/helpers/toggle.rb:10
module Byebug::Helpers::ToggleHelper
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/helpers/toggle.rb:13
  def enable_disable_breakpoints(is_enable, args); end

  # pkg:gem/byebug#lib/byebug/helpers/toggle.rb:26
  def enable_disable_display(is_enable, args); end

  private

  # pkg:gem/byebug#lib/byebug/helpers/toggle.rb:57
  def n_displays; end

  # pkg:gem/byebug#lib/byebug/helpers/toggle.rb:41
  def select_breakpoints(is_enable, args); end
end

# Utilities for variable subcommands
#
# pkg:gem/byebug#lib/byebug/helpers/var.rb:10
module Byebug::Helpers::VarHelper
  include ::Byebug::Helpers::EvalHelper

  # pkg:gem/byebug#lib/byebug/helpers/var.rb:58
  def var_args; end

  # pkg:gem/byebug#lib/byebug/helpers/var.rb:37
  def var_global; end

  # pkg:gem/byebug#lib/byebug/helpers/var.rb:45
  def var_instance(str); end

  # pkg:gem/byebug#lib/byebug/helpers/var.rb:13
  def var_list(ary, binding = T.unsafe(nil)); end

  # pkg:gem/byebug#lib/byebug/helpers/var.rb:51
  def var_local; end
end

# Setting to customize the file where byebug's history is saved.
#
# pkg:gem/byebug#lib/byebug/settings/histfile.rb:9
class Byebug::HistfileSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/histfile.rb:12
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/histfile.rb:16
  def to_s; end
end

# pkg:gem/byebug#lib/byebug/settings/histfile.rb:10
Byebug::HistfileSetting::DEFAULT = T.let(T.unsafe(nil), String)

# Handles byebug's history of commands.
#
# pkg:gem/byebug#lib/byebug/history.rb:9
class Byebug::History
  # pkg:gem/byebug#lib/byebug/history.rb:12
  def initialize; end

  # Array holding the list of commands in history
  #
  # pkg:gem/byebug#lib/byebug/history.rb:19
  def buffer; end

  # Discards history.
  #
  # pkg:gem/byebug#lib/byebug/history.rb:48
  def clear; end

  # Max number of commands to be displayed when no size has been specified.
  #
  # Never more than Setting[:histsize].
  #
  # pkg:gem/byebug#lib/byebug/history.rb:95
  def default_max_size; end

  # Whether a specific command should not be stored in history.
  #
  # For now, empty lines and consecutive duplicates.
  #
  # pkg:gem/byebug#lib/byebug/history.rb:113
  def ignore?(buf); end

  # Array of ids of the last +number+ commands.
  #
  # pkg:gem/byebug#lib/byebug/history.rb:86
  def last_ids(number); end

  # Removes a command from Reline's history.
  #
  # pkg:gem/byebug#lib/byebug/history.rb:65
  def pop; end

  # Adds a new command to Reline's history.
  #
  # pkg:gem/byebug#lib/byebug/history.rb:55
  def push(cmd); end

  # Restores history from disk.
  #
  # pkg:gem/byebug#lib/byebug/history.rb:26
  def restore; end

  # Saves history to disk.
  #
  # pkg:gem/byebug#lib/byebug/history.rb:35
  def save; end

  # pkg:gem/byebug#lib/byebug/history.rb:10
  def size; end

  # Max number of commands to be displayed when a size has been specified.
  #
  # The only bound here is not showing more items than available.
  #
  # pkg:gem/byebug#lib/byebug/history.rb:104
  def specific_max_size(number); end

  # Prints the requested numbers of history entries.
  #
  # pkg:gem/byebug#lib/byebug/history.rb:73
  def to_s(n_cmds); end
end

# Show history of byebug commands.
#
# pkg:gem/byebug#lib/byebug/commands/history.rb:10
class Byebug::HistoryCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/history.rb:31
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/history.rb:19
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/history.rb:15
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/history.rb:27
    def short_description; end
  end
end

# Setting to customize the number of byebug commands to be saved in history.
#
# pkg:gem/byebug#lib/byebug/settings/histsize.rb:9
class Byebug::HistsizeSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/histsize.rb:12
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/histsize.rb:16
  def to_s; end
end

# pkg:gem/byebug#lib/byebug/settings/histsize.rb:10
Byebug::HistsizeSetting::DEFAULT = T.let(T.unsafe(nil), Integer)

# Shows info about different aspects of the debugger.
#
#
# Reopens the +info+ command to define the +breakpoints+ subcommand
#
#
# Reopens the +info+ command to define the +display+ subcommand
#
#
# Reopens the +info+ command to define the +file+ subcommand
#
#
# Reopens the +info+ command to define the +line+ subcommand
#
#
# Reopens the +info+ command to define the +args+ subcommand
#
# pkg:gem/byebug#lib/byebug/commands/info/breakpoints.rb:7
class Byebug::InfoCommand < ::Byebug::Command
  include ::Byebug::Subcommands
  extend ::Byebug::Helpers::ReflectionHelper
  extend ::Byebug::Subcommands::ClassMethods

  class << self
    # pkg:gem/byebug#lib/byebug/commands/info.rb:25
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/info.rb:21
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/info.rb:33
    def short_description; end
  end
end

# Information about current breakpoints
#
# pkg:gem/byebug#lib/byebug/commands/info/breakpoints.rb:11
class Byebug::InfoCommand::BreakpointsCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/info/breakpoints.rb:30
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/info/breakpoints.rb:47
  def info_breakpoint(brkpt); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/info/breakpoints.rb:18
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/info/breakpoints.rb:14
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/info/breakpoints.rb:26
    def short_description; end
  end
end

# Information about display expressions
#
# pkg:gem/byebug#lib/byebug/commands/info/display.rb:11
class Byebug::InfoCommand::DisplayCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/info/display.rb:30
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/info/display.rb:18
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/info/display.rb:14
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/info/display.rb:26
    def short_description; end
  end
end

# Information about a particular source file
#
# pkg:gem/byebug#lib/byebug/commands/info/file.rb:13
class Byebug::InfoCommand::FileCommand < ::Byebug::Command
  include ::Byebug::Helpers::FileHelper
  include ::Byebug::Helpers::StringHelper

  # pkg:gem/byebug#lib/byebug/commands/info/file.rb:38
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/info/file.rb:55
  def info_file_basic(file); end

  # pkg:gem/byebug#lib/byebug/commands/info/file.rb:63
  def info_file_breakpoints(file); end

  # pkg:gem/byebug#lib/byebug/commands/info/file.rb:70
  def info_file_mtime(file); end

  # pkg:gem/byebug#lib/byebug/commands/info/file.rb:74
  def info_file_sha1(file); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/info/file.rb:23
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/info/file.rb:19
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/info/file.rb:34
    def short_description; end
  end
end

# Information about current location
#
# pkg:gem/byebug#lib/byebug/commands/info/line.rb:11
class Byebug::InfoCommand::LineCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/info/line.rb:30
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/info/line.rb:18
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/info/line.rb:14
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/info/line.rb:26
    def short_description; end
  end
end

# Information about arguments of the current method/block
#
# pkg:gem/byebug#lib/byebug/commands/info/program.rb:11
class Byebug::InfoCommand::ProgramCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/info/program.rb:30
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/info/program.rb:37
  def format_stop_reason(stop_reason); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/info/program.rb:18
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/info/program.rb:14
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/info/program.rb:26
    def short_description; end
  end
end

# Main Interface class
#
# Contains common functionality to all implemented interfaces.
#
# pkg:gem/byebug#lib/byebug/interface.rb:16
class Byebug::Interface
  include ::Byebug::Helpers::FileHelper

  # pkg:gem/byebug#lib/byebug/interface.rb:22
  def initialize; end

  # Restores history according to +autosave+ setting.
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:118
  def autorestore; end

  # Saves or clears history according to +autosave+ setting.
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:111
  def autosave; end

  # pkg:gem/byebug#lib/byebug/interface.rb:105
  def close; end

  # pkg:gem/byebug#lib/byebug/interface.rb:19
  def command_queue; end

  # pkg:gem/byebug#lib/byebug/interface.rb:19
  def command_queue=(_arg0); end

  # Confirms user introduced an affirmative response to the input stream.
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:101
  def confirm(prompt); end

  # Prints an error message to the error stream.
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:80
  def errmsg(message); end

  # pkg:gem/byebug#lib/byebug/interface.rb:20
  def error; end

  # pkg:gem/byebug#lib/byebug/interface.rb:19
  def history; end

  # pkg:gem/byebug#lib/byebug/interface.rb:19
  def history=(_arg0); end

  # pkg:gem/byebug#lib/byebug/interface.rb:20
  def input; end

  # pkg:gem/byebug#lib/byebug/interface.rb:28
  def last_if_empty(input); end

  # pkg:gem/byebug#lib/byebug/interface.rb:20
  def output; end

  # Reads a new line from the interface's input stream.
  #
  # @return [String] New string read or the previous string if the string
  # read now was empty.
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:70
  def prepare_input(prompt); end

  # Prints an output message to the output stream without a final "\n".
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:94
  def print(message); end

  # Prints an output message to the output stream.
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:87
  def puts(message); end

  # Pops a command from the input stream.
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:35
  def read_command(prompt); end

  # Pushes lines in +filename+ to the command queue.
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:44
  def read_file(filename); end

  # Reads a new line from the interface's input stream, parses it into
  # commands and saves it to history.
  #
  # @return [String] Representing something to be run by the debugger.
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:54
  def read_input(prompt, save_hist = T.unsafe(nil)); end

  private

  # Splits a command line of the form "cmd1 ; cmd2 ; ... ; cmdN" into an
  # array of commands: [cmd1, cmd2, ..., cmdN]
  #
  # pkg:gem/byebug#lib/byebug/interface.rb:128
  def split_commands(cmd_line); end
end

# Interrupting execution of current thread.
#
# pkg:gem/byebug#lib/byebug/commands/interrupt.rb:9
class Byebug::InterruptCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/interrupt.rb:28
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/interrupt.rb:16
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/interrupt.rb:12
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/interrupt.rb:24
    def short_description; end
  end
end

# Enter IRB from byebug's prompt
#
# pkg:gem/byebug#lib/byebug/commands/irb.rb:10
class Byebug::IrbCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/irb.rb:29
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/irb.rb:41
  def with_clean_argv; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/irb.rb:17
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/irb.rb:13
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/irb.rb:25
    def short_description; end
  end
end

# Send custom signals to the debugged program.
#
# pkg:gem/byebug#lib/byebug/commands/kill.rb:9
class Byebug::KillCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/kill.rb:30
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/kill.rb:16
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/kill.rb:12
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/kill.rb:26
    def short_description; end
  end
end

# Setting to enable/disable linetracing.
#
# pkg:gem/byebug#lib/byebug/settings/linetrace.rb:9
class Byebug::LinetraceSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/linetrace.rb:10
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/linetrace.rb:18
  def value; end

  # pkg:gem/byebug#lib/byebug/settings/linetrace.rb:14
  def value=(val); end
end

# List parts of the source code.
#
# pkg:gem/byebug#lib/byebug/commands/list.rb:12
class Byebug::ListCommand < ::Byebug::Command
  include ::Byebug::Helpers::FileHelper
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/list.rb:150
  def amend_final(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/commands/list.rb:40
  def execute; end

  # pkg:gem/byebug#lib/byebug/commands/list.rb:150
  def max_line(*args, **_arg1, &block); end

  # pkg:gem/byebug#lib/byebug/commands/list.rb:150
  def size(*args, **_arg1, &block); end

  private

  # Set line range to be printed by list
  #
  # @return first line number to list
  # @return last line number to list
  #
  # pkg:gem/byebug#lib/byebug/commands/list.rb:79
  def auto_range(direction); end

  # Show a range of lines in the current file.
  #
  # @param min [Integer] Lower bound
  # @param max [Integer] Upper bound
  #
  # pkg:gem/byebug#lib/byebug/commands/list.rb:115
  def display_lines(min, max); end

  # @param range [String] A string with an integer range format
  #
  # @return [String] The lower bound of the given range
  #
  # pkg:gem/byebug#lib/byebug/commands/list.rb:126
  def lower_bound(range); end

  # pkg:gem/byebug#lib/byebug/commands/list.rb:105
  def move(line, size, direction = T.unsafe(nil)); end

  # pkg:gem/byebug#lib/byebug/commands/list.rb:89
  def parse_range(input); end

  # Line range to be printed by `list`.
  #
  # If <input> is set, range is parsed from it.
  #
  # Otherwise it's automatically chosen.
  #
  # pkg:gem/byebug#lib/byebug/commands/list.rb:60
  def range(input); end

  # pkg:gem/byebug#lib/byebug/commands/list.rb:152
  def source_file_formatter; end

  # @param str [String] A string with an integer range format
  #
  # @return [Array] The upper & lower bounds of the given range
  #
  # pkg:gem/byebug#lib/byebug/commands/list.rb:144
  def split_range(str); end

  # @param range [String] A string with an integer range format
  #
  # @return [String] The upper bound of the given range
  #
  # pkg:gem/byebug#lib/byebug/commands/list.rb:135
  def upper_bound(range); end

  # pkg:gem/byebug#lib/byebug/commands/list.rb:69
  def valid_range?(first, last); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/list.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/list.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/list.rb:36
    def short_description; end
  end
end

# Setting to customize the number of source code lines to be displayed every
# time the "list" command is invoked.
#
# pkg:gem/byebug#lib/byebug/settings/listsize.rb:10
class Byebug::ListsizeSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/listsize.rb:13
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/listsize.rb:17
  def to_s; end
end

# pkg:gem/byebug#lib/byebug/settings/listsize.rb:11
Byebug::ListsizeSetting::DEFAULT = T.let(T.unsafe(nil), Integer)

# Interface class for standard byebug use.
#
# pkg:gem/byebug#lib/byebug/interfaces/local_interface.rb:7
class Byebug::LocalInterface < ::Byebug::Interface
  # pkg:gem/byebug#lib/byebug/interfaces/local_interface.rb:10
  def initialize; end

  # Reads a single line of input using Reline. If Ctrl-D is pressed, it
  # returns "continue", meaning that program's execution will go on.
  #
  # @param prompt Prompt to be displayed.
  #
  # pkg:gem/byebug#lib/byebug/interfaces/local_interface.rb:23
  def readline(prompt); end

  # Yields the block handling Ctrl-C the following way: if pressed while
  # waiting for input, the line is reset to only the prompt and we ask for
  # input again.
  #
  # @note Any external 'INT' traps are overriden during this method.
  #
  # pkg:gem/byebug#lib/byebug/interfaces/local_interface.rb:34
  def with_repl_like_sigint; end

  # Disable any Reline completion procs.
  #
  # Other gems, for example, IRB could've installed completion procs that are
  # dependent on them being loaded. Disable those while byebug is the REPL
  # making use of Reline.
  #
  # pkg:gem/byebug#lib/byebug/interfaces/local_interface.rb:51
  def without_reline_completion; end
end

# pkg:gem/byebug#lib/byebug/interfaces/local_interface.rb:8
Byebug::LocalInterface::EOF_ALIAS = T.let(T.unsafe(nil), String)

# Show methods of specific classes/modules/objects.
#
# pkg:gem/byebug#lib/byebug/commands/method.rb:10
class Byebug::MethodCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper

  # pkg:gem/byebug#lib/byebug/commands/method.rb:37
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/method.rb:19
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/method.rb:15
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/method.rb:33
    def short_description; end
  end
end

# Implements the next functionality.
#
# Allows the user the continue execution until the next instruction in the
# current frame.
#
# pkg:gem/byebug#lib/byebug/commands/next.rb:13
class Byebug::NextCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/next.rb:32
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/next.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/next.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/next.rb:28
    def short_description; end
  end
end

# Port number used for remote debugging
#
# pkg:gem/byebug#lib/byebug/remote.rb:13
Byebug::PORT = T.let(T.unsafe(nil), Integer)

# Processes commands in post_mortem mode
#
# pkg:gem/byebug#lib/byebug/processors/post_mortem_processor.rb:9
class Byebug::PostMortemProcessor < ::Byebug::CommandProcessor
  # pkg:gem/byebug#lib/byebug/processors/post_mortem_processor.rb:10
  def commands; end

  # pkg:gem/byebug#lib/byebug/processors/post_mortem_processor.rb:14
  def prompt; end
end

# Setting to enable/disable post_mortem mode, i.e., a debugger prompt after
# program termination by unhandled exception.
#
# pkg:gem/byebug#lib/byebug/settings/post_mortem.rb:10
class Byebug::PostMortemSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/post_mortem.rb:11
  def initialize; end

  # pkg:gem/byebug#lib/byebug/settings/post_mortem.rb:15
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/post_mortem.rb:23
  def value; end

  # pkg:gem/byebug#lib/byebug/settings/post_mortem.rb:19
  def value=(val); end
end

# pkg:gem/byebug#lib/byebug/printers/base.rb:6
module Byebug::Printers; end

# Base printer
#
# pkg:gem/byebug#lib/byebug/printers/base.rb:10
class Byebug::Printers::Base
  # pkg:gem/byebug#lib/byebug/printers/base.rb:16
  def type; end

  private

  # pkg:gem/byebug#lib/byebug/printers/base.rb:55
  def array_of_args(collection, &_block); end

  # pkg:gem/byebug#lib/byebug/printers/base.rb:49
  def contents; end

  # pkg:gem/byebug#lib/byebug/printers/base.rb:63
  def contents_files; end

  # pkg:gem/byebug#lib/byebug/printers/base.rb:22
  def locate(path); end

  # pkg:gem/byebug#lib/byebug/printers/base.rb:45
  def parts(path); end

  # pkg:gem/byebug#lib/byebug/printers/base.rb:35
  def translate(string, args = T.unsafe(nil)); end
end

# pkg:gem/byebug#lib/byebug/printers/base.rb:12
class Byebug::Printers::Base::MissedArgument < ::StandardError; end

# pkg:gem/byebug#lib/byebug/printers/base.rb:11
class Byebug::Printers::Base::MissedPath < ::StandardError; end

# pkg:gem/byebug#lib/byebug/printers/base.rb:14
Byebug::Printers::Base::SEPARATOR = T.let(T.unsafe(nil), String)

# Plain text printer
#
# pkg:gem/byebug#lib/byebug/printers/plain.rb:10
class Byebug::Printers::Plain < ::Byebug::Printers::Base
  # pkg:gem/byebug#lib/byebug/printers/plain.rb:11
  def print(path, args = T.unsafe(nil)); end

  # pkg:gem/byebug#lib/byebug/printers/plain.rb:17
  def print_collection(path, collection, &block); end

  # pkg:gem/byebug#lib/byebug/printers/plain.rb:25
  def print_variables(variables, *_unused); end

  private

  # pkg:gem/byebug#lib/byebug/printers/plain.rb:39
  def contents_files; end
end

# Enter Pry from byebug's prompt
#
# pkg:gem/byebug#lib/byebug/commands/pry.rb:10
class Byebug::PryCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/pry.rb:29
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/pry.rb:17
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/pry.rb:13
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/pry.rb:25
    def short_description; end
  end
end

# Exit from byebug.
#
# pkg:gem/byebug#lib/byebug/commands/quit.rb:9
class Byebug::QuitCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/quit.rb:33
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/quit.rb:17
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/quit.rb:13
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/quit.rb:29
    def short_description; end
  end
end

# pkg:gem/byebug#lib/byebug/remote/server.rb:6
module Byebug::Remote; end

# Client for remote debugging
#
# pkg:gem/byebug#lib/byebug/remote/client.rb:10
class Byebug::Remote::Client
  # pkg:gem/byebug#lib/byebug/remote/client.rb:13
  def initialize(interface); end

  # pkg:gem/byebug#lib/byebug/remote/client.rb:11
  def interface; end

  # pkg:gem/byebug#lib/byebug/remote/client.rb:11
  def socket; end

  # Connects to the remote byebug
  #
  # pkg:gem/byebug#lib/byebug/remote/client.rb:21
  def start(host = T.unsafe(nil), port = T.unsafe(nil)); end

  # pkg:gem/byebug#lib/byebug/remote/client.rb:44
  def started?; end

  private

  # pkg:gem/byebug#lib/byebug/remote/client.rb:50
  def connect_at(host, port); end
end

# Server for remote debugging
#
# pkg:gem/byebug#lib/byebug/remote/server.rb:10
class Byebug::Remote::Server
  # pkg:gem/byebug#lib/byebug/remote/server.rb:13
  def initialize(wait_connection:, &block); end

  # pkg:gem/byebug#lib/byebug/remote/server.rb:11
  def actual_port; end

  # Start the remote debugging server
  #
  # pkg:gem/byebug#lib/byebug/remote/server.rb:22
  def start(host, port); end

  # pkg:gem/byebug#lib/byebug/remote/server.rb:11
  def wait_connection; end
end

# Interface class for remote use of byebug.
#
# pkg:gem/byebug#lib/byebug/interfaces/remote_interface.rb:9
class Byebug::RemoteInterface < ::Byebug::Interface
  # pkg:gem/byebug#lib/byebug/interfaces/remote_interface.rb:10
  def initialize(socket); end

  # pkg:gem/byebug#lib/byebug/interfaces/remote_interface.rb:41
  def close; end

  # pkg:gem/byebug#lib/byebug/interfaces/remote_interface.rb:23
  def confirm(prompt); end

  # pkg:gem/byebug#lib/byebug/interfaces/remote_interface.rb:29
  def print(message); end

  # pkg:gem/byebug#lib/byebug/interfaces/remote_interface.rb:35
  def puts(message); end

  # pkg:gem/byebug#lib/byebug/interfaces/remote_interface.rb:17
  def read_command(prompt); end

  # pkg:gem/byebug#lib/byebug/interfaces/remote_interface.rb:45
  def readline(prompt); end
end

# Restart debugged program from within byebug.
#
# pkg:gem/byebug#lib/byebug/commands/restart.rb:14
class Byebug::RestartCommand < ::Byebug::Command
  include ::Byebug::Helpers::BinHelper
  include ::Byebug::Helpers::PathHelper

  # pkg:gem/byebug#lib/byebug/commands/restart.rb:40
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/restart.rb:54
  def prepend_byebug_bin(cmd); end

  # pkg:gem/byebug#lib/byebug/commands/restart.rb:59
  def prepend_ruby_bin(cmd); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/restart.rb:25
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/restart.rb:21
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/restart.rb:36
    def short_description; end
  end
end

# Save current settings to use them in another debug session.
#
# pkg:gem/byebug#lib/byebug/commands/save.rb:9
class Byebug::SaveCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/save.rb:36
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/save.rb:50
  def save_breakpoints(file); end

  # pkg:gem/byebug#lib/byebug/commands/save.rb:56
  def save_catchpoints(file); end

  # pkg:gem/byebug#lib/byebug/commands/save.rb:62
  def save_displays(file); end

  # pkg:gem/byebug#lib/byebug/commands/save.rb:66
  def save_settings(file); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/save.rb:17
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/save.rb:13
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/save.rb:32
    def short_description; end
  end
end

# Setting to customize the file where byebug's settings are saved.
#
# pkg:gem/byebug#lib/byebug/settings/savefile.rb:9
class Byebug::SavefileSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/savefile.rb:12
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/savefile.rb:16
  def to_s; end
end

# pkg:gem/byebug#lib/byebug/settings/savefile.rb:10
Byebug::SavefileSetting::DEFAULT = T.let(T.unsafe(nil), String)

# Interface class for command execution from script files.
#
# pkg:gem/byebug#lib/byebug/interfaces/script_interface.rb:7
class Byebug::ScriptInterface < ::Byebug::Interface
  # pkg:gem/byebug#lib/byebug/interfaces/script_interface.rb:8
  def initialize(file, verbose = T.unsafe(nil)); end

  # pkg:gem/byebug#lib/byebug/interfaces/script_interface.rb:20
  def close; end

  # pkg:gem/byebug#lib/byebug/interfaces/script_interface.rb:16
  def read_command(prompt); end

  # pkg:gem/byebug#lib/byebug/interfaces/script_interface.rb:24
  def readline(*_arg0); end
end

# Processes commands from a file
#
# pkg:gem/byebug#lib/byebug/processors/script_processor.rb:9
class Byebug::ScriptProcessor < ::Byebug::CommandProcessor
  # pkg:gem/byebug#lib/byebug/processors/script_processor.rb:28
  def after_repl; end

  # Available commands
  #
  # pkg:gem/byebug#lib/byebug/processors/script_processor.rb:13
  def commands; end

  # Prompt shown before reading a command.
  #
  # pkg:gem/byebug#lib/byebug/processors/script_processor.rb:37
  def prompt; end

  # pkg:gem/byebug#lib/byebug/processors/script_processor.rb:17
  def repl; end

  private

  # pkg:gem/byebug#lib/byebug/processors/script_processor.rb:43
  def without_exceptions; end
end

# Change byebug settings.
#
# pkg:gem/byebug#lib/byebug/commands/set.rb:10
class Byebug::SetCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/set.rb:42
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/set.rb:66
  def get_onoff(arg, default); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/set.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/set.rb:38
    def help; end

    # pkg:gem/byebug#lib/byebug/commands/set.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/set.rb:34
    def short_description; end
  end
end

# Parent class for all byebug settings.
#
# pkg:gem/byebug#lib/byebug/setting.rb:9
class Byebug::Setting
  # pkg:gem/byebug#lib/byebug/setting.rb:14
  def initialize; end

  # pkg:gem/byebug#lib/byebug/setting.rb:18
  def boolean?; end

  # pkg:gem/byebug#lib/byebug/setting.rb:28
  def help; end

  # pkg:gem/byebug#lib/byebug/setting.rb:22
  def integer?; end

  # pkg:gem/byebug#lib/byebug/setting.rb:37
  def to_s; end

  # pkg:gem/byebug#lib/byebug/setting.rb:32
  def to_sym; end

  # pkg:gem/byebug#lib/byebug/setting.rb:10
  def value; end

  # pkg:gem/byebug#lib/byebug/setting.rb:10
  def value=(_arg0); end

  class << self
    # pkg:gem/byebug#lib/byebug/setting.rb:46
    def [](name); end

    # pkg:gem/byebug#lib/byebug/setting.rb:50
    def []=(name, value); end

    # pkg:gem/byebug#lib/byebug/setting.rb:54
    def find(shortcut); end

    # @todo DRY this up. Very similar code exists in the CommandList class
    #
    # pkg:gem/byebug#lib/byebug/setting.rb:65
    def help_all; end

    # pkg:gem/byebug#lib/byebug/setting.rb:42
    def settings; end
  end
end

# pkg:gem/byebug#lib/byebug/setting.rb:12
Byebug::Setting::DEFAULT = T.let(T.unsafe(nil), FalseClass)

# Show byebug settings.
#
# pkg:gem/byebug#lib/byebug/commands/show.rb:9
class Byebug::ShowCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/show.rb:35
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/show.rb:17
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/show.rb:31
    def help; end

    # pkg:gem/byebug#lib/byebug/commands/show.rb:13
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/show.rb:27
    def short_description; end
  end
end

# Allows the user to continue execution until the next breakpoint, as
# long as it is different from the current one
#
# pkg:gem/byebug#lib/byebug/commands/skip.rb:11
class Byebug::SkipCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/skip.rb:70
  def auto_run; end

  # pkg:gem/byebug#lib/byebug/commands/skip.rb:77
  def execute; end

  # pkg:gem/byebug#lib/byebug/commands/skip.rb:53
  def initialize_attributes; end

  # pkg:gem/byebug#lib/byebug/commands/skip.rb:60
  def keep_execution; end

  # pkg:gem/byebug#lib/byebug/commands/skip.rb:64
  def reset_attributes; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/skip.rb:41
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/skip.rb:18
    def file_line; end

    # pkg:gem/byebug#lib/byebug/commands/skip.rb:15
    def file_line=(_arg0); end

    # pkg:gem/byebug#lib/byebug/commands/skip.rb:22
    def file_path; end

    # pkg:gem/byebug#lib/byebug/commands/skip.rb:15
    def file_path=(_arg0); end

    # pkg:gem/byebug#lib/byebug/commands/skip.rb:16
    def previous_autolist; end

    # pkg:gem/byebug#lib/byebug/commands/skip.rb:37
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/skip.rb:31
    def restore_autolist; end

    # pkg:gem/byebug#lib/byebug/commands/skip.rb:26
    def setup_autolist(value); end

    # pkg:gem/byebug#lib/byebug/commands/skip.rb:49
    def short_description; end
  end
end

# Execute a file containing byebug commands.
#
# It can be used to restore a previously saved debugging session.
#
# pkg:gem/byebug#lib/byebug/commands/source.rb:11
class Byebug::SourceCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/source.rb:31
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/source.rb:19
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/source.rb:15
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/source.rb:27
    def short_description; end
  end
end

# Formats specific line ranges in a source file
#
# pkg:gem/byebug#lib/byebug/source_file_formatter.rb:10
class Byebug::SourceFileFormatter
  include ::Byebug::Helpers::FileHelper

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:15
  def initialize(file, annotator); end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:67
  def amend(line, ceiling); end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:51
  def amend_final(line); end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:47
  def amend_initial(line); end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:13
  def annotator; end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:13
  def file; end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:20
  def lines(min, max); end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:33
  def lines_around(center); end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:55
  def max_initial_line; end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:59
  def max_line; end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:37
  def range_around(center); end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:41
  def range_from(min); end

  # pkg:gem/byebug#lib/byebug/source_file_formatter.rb:63
  def size; end
end

# Setting to enable/disable the display of backtraces when evaluations raise
# errors.
#
# pkg:gem/byebug#lib/byebug/settings/stack_on_error.rb:10
class Byebug::StackOnErrorSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/stack_on_error.rb:11
  def banner; end
end

# Implements the step functionality.
#
# Allows the user the continue execution until the next instruction, possibly
# in a different frame. Use step to step into method calls or blocks.
#
# pkg:gem/byebug#lib/byebug/commands/step.rb:13
class Byebug::StepCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/step.rb:32
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/step.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/step.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/step.rb:28
    def short_description; end
  end
end

# Subcommand additions.
#
# pkg:gem/byebug#lib/byebug/subcommands.rb:12
module Byebug::Subcommands
  extend ::Forwardable

  mixes_in_class_methods ::Byebug::Subcommands::ClassMethods

  # Delegates to subcommands or prints help if no subcommand specified.
  #
  # pkg:gem/byebug#lib/byebug/subcommands.rb:23
  def execute; end

  # pkg:gem/byebug#lib/byebug/subcommands.rb:18
  def subcommand_list(*args, **_arg1, &block); end

  class << self
    # pkg:gem/byebug#lib/byebug/subcommands.rb:13
    def included(command); end
  end
end

# Class methods added to subcommands
#
# pkg:gem/byebug#lib/byebug/subcommands.rb:36
module Byebug::Subcommands::ClassMethods
  include ::Byebug::Helpers::ReflectionHelper

  # Default help text for a command with subcommands
  #
  # pkg:gem/byebug#lib/byebug/subcommands.rb:42
  def help; end

  # Command's subcommands.
  #
  # pkg:gem/byebug#lib/byebug/subcommands.rb:49
  def subcommand_list; end
end

# Manipulation of Ruby threads
#
#
# Reopens the +thread+ command to define the +current+ subcommand
#
#
# Reopens the +thread+ command to define the +list+ subcommand
#
#
# Reopens the +thread+ command to define the +resume+ subcommand
#
#
# Reopens the +thread+ command to define the +stop+ subcommand
#
#
# Reopens the +thread+ command to define the +switch+ subcommand
#
# pkg:gem/byebug#lib/byebug/commands/thread/current.rb:9
class Byebug::ThreadCommand < ::Byebug::Command
  include ::Byebug::Subcommands
  extend ::Byebug::Helpers::ReflectionHelper
  extend ::Byebug::Subcommands::ClassMethods

  class << self
    # pkg:gem/byebug#lib/byebug/commands/thread.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/thread.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/thread.rb:30
    def short_description; end
  end
end

# Information about the current thread
#
# pkg:gem/byebug#lib/byebug/commands/thread/current.rb:13
class Byebug::ThreadCommand::CurrentCommand < ::Byebug::Command
  include ::Byebug::Helpers::ThreadHelper

  # pkg:gem/byebug#lib/byebug/commands/thread/current.rb:32
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/thread/current.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/thread/current.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/thread/current.rb:28
    def short_description; end
  end
end

# Information about threads
#
# pkg:gem/byebug#lib/byebug/commands/thread/list.rb:13
class Byebug::ThreadCommand::ListCommand < ::Byebug::Command
  include ::Byebug::Helpers::ThreadHelper

  # pkg:gem/byebug#lib/byebug/commands/thread/list.rb:32
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/thread/list.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/thread/list.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/thread/list.rb:28
    def short_description; end
  end
end

# Resumes the specified thread
#
# pkg:gem/byebug#lib/byebug/commands/thread/resume.rb:13
class Byebug::ThreadCommand::ResumeCommand < ::Byebug::Command
  include ::Byebug::Helpers::ThreadHelper

  # pkg:gem/byebug#lib/byebug/commands/thread/resume.rb:32
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/thread/resume.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/thread/resume.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/thread/resume.rb:28
    def short_description; end
  end
end

# Stops the specified thread
#
# pkg:gem/byebug#lib/byebug/commands/thread/stop.rb:13
class Byebug::ThreadCommand::StopCommand < ::Byebug::Command
  include ::Byebug::Helpers::ThreadHelper

  # pkg:gem/byebug#lib/byebug/commands/thread/stop.rb:32
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/thread/stop.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/thread/stop.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/thread/stop.rb:28
    def short_description; end
  end
end

# Switches to the specified thread
#
# pkg:gem/byebug#lib/byebug/commands/thread/switch.rb:13
class Byebug::ThreadCommand::SwitchCommand < ::Byebug::Command
  include ::Byebug::Helpers::ThreadHelper

  # pkg:gem/byebug#lib/byebug/commands/thread/switch.rb:32
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/thread/switch.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/thread/switch.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/thread/switch.rb:28
    def short_description; end
  end
end

class Byebug::ThreadsTable; end

# Show (and possibly stop) at every line that changes a global variable.
#
# pkg:gem/byebug#lib/byebug/commands/tracevar.rb:9
class Byebug::TracevarCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/tracevar.rb:32
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/tracevar.rb:48
  def on_change(name, value, stop); end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/tracevar.rb:16
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/tracevar.rb:10
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/tracevar.rb:28
    def short_description; end
  end
end

# Remove expressions from display list.
#
# pkg:gem/byebug#lib/byebug/commands/undisplay.rb:10
class Byebug::UndisplayCommand < ::Byebug::Command
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/undisplay.rb:35
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/undisplay.rb:19
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/undisplay.rb:15
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/undisplay.rb:31
    def short_description; end
  end
end

# Stop tracing a global variable.
#
# pkg:gem/byebug#lib/byebug/commands/untracevar.rb:9
class Byebug::UntracevarCommand < ::Byebug::Command
  # pkg:gem/byebug#lib/byebug/commands/untracevar.rb:26
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/untracevar.rb:14
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/untracevar.rb:10
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/untracevar.rb:22
    def short_description; end
  end
end

# Move the current frame up in the backtrace.
#
# pkg:gem/byebug#lib/byebug/commands/up.rb:12
class Byebug::UpCommand < ::Byebug::Command
  include ::Byebug::Helpers::FrameHelper
  include ::Byebug::Helpers::ParseHelper

  # pkg:gem/byebug#lib/byebug/commands/up.rb:36
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/up.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/up.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/up.rb:32
    def short_description; end
  end
end

# Shows variables and its values
#
#
# Reopens the +var+ command to define the +all+ subcommand
#
#
# Reopens the +var+ command to define the +args+ subcommand
#
#
# Reopens the +var+ command to define the +const+ subcommand
#
#
# Reopens the +var+ command to define the +global+ subcommand
#
#
# Reopens the +var+ command to define the +instance+ subcommand
#
#
# Reopens the +var+ command to define the +local+ subcommand
#
# pkg:gem/byebug#lib/byebug/commands/var/all.rb:9
class Byebug::VarCommand < ::Byebug::Command
  include ::Byebug::Subcommands
  extend ::Byebug::Helpers::ReflectionHelper
  extend ::Byebug::Subcommands::ClassMethods

  class << self
    # pkg:gem/byebug#lib/byebug/commands/var.rb:25
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/var.rb:21
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/var.rb:33
    def short_description; end
  end
end

# Shows global, instance and local variables
#
# pkg:gem/byebug#lib/byebug/commands/var/all.rb:13
class Byebug::VarCommand::AllCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper
  include ::Byebug::Helpers::VarHelper

  # pkg:gem/byebug#lib/byebug/commands/var/all.rb:34
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/var/all.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/var/all.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/var/all.rb:30
    def short_description; end
  end
end

# Information about arguments of the current method/block
#
# pkg:gem/byebug#lib/byebug/commands/var/args.rb:13
class Byebug::VarCommand::ArgsCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper
  include ::Byebug::Helpers::VarHelper

  # pkg:gem/byebug#lib/byebug/commands/var/args.rb:34
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/var/args.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/var/args.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/var/args.rb:30
    def short_description; end
  end
end

# Shows constants
#
# pkg:gem/byebug#lib/byebug/commands/var/const.rb:13
class Byebug::VarCommand::ConstCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper

  # pkg:gem/byebug#lib/byebug/commands/var/const.rb:34
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/var/const.rb:44
  def str_obj; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/var/const.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/var/const.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/var/const.rb:30
    def short_description; end
  end
end

# Shows global variables
#
# pkg:gem/byebug#lib/byebug/commands/var/global.rb:11
class Byebug::VarCommand::GlobalCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper
  include ::Byebug::Helpers::VarHelper

  # pkg:gem/byebug#lib/byebug/commands/var/global.rb:32
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/var/global.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/var/global.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/var/global.rb:28
    def short_description; end
  end
end

# Shows instance variables
#
# pkg:gem/byebug#lib/byebug/commands/var/instance.rb:13
class Byebug::VarCommand::InstanceCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper
  include ::Byebug::Helpers::VarHelper

  # pkg:gem/byebug#lib/byebug/commands/var/instance.rb:34
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/var/instance.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/var/instance.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/var/instance.rb:30
    def short_description; end
  end
end

# Shows local variables in current scope
#
# pkg:gem/byebug#lib/byebug/commands/var/local.rb:13
class Byebug::VarCommand::LocalCommand < ::Byebug::Command
  include ::Byebug::Helpers::EvalHelper
  include ::Byebug::Helpers::VarHelper

  # pkg:gem/byebug#lib/byebug/commands/var/local.rb:34
  def execute; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/var/local.rb:22
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/var/local.rb:18
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/var/local.rb:30
    def short_description; end
  end
end

# Show current backtrace.
#
# pkg:gem/byebug#lib/byebug/commands/where.rb:11
class Byebug::WhereCommand < ::Byebug::Command
  include ::Byebug::Helpers::FrameHelper

  # pkg:gem/byebug#lib/byebug/commands/where.rb:43
  def execute; end

  private

  # pkg:gem/byebug#lib/byebug/commands/where.rb:49
  def print_backtrace; end

  class << self
    # pkg:gem/byebug#lib/byebug/commands/where.rb:20
    def description; end

    # pkg:gem/byebug#lib/byebug/commands/where.rb:16
    def regexp; end

    # pkg:gem/byebug#lib/byebug/commands/where.rb:39
    def short_description; end
  end
end

# Setting to customize the maximum width of byebug's output.
#
# pkg:gem/byebug#lib/byebug/settings/width.rb:9
class Byebug::WidthSetting < ::Byebug::Setting
  # pkg:gem/byebug#lib/byebug/settings/width.rb:12
  def banner; end

  # pkg:gem/byebug#lib/byebug/settings/width.rb:16
  def to_s; end
end

# pkg:gem/byebug#lib/byebug/settings/width.rb:10
Byebug::WidthSetting::DEFAULT = T.let(T.unsafe(nil), Integer)

# Extends the extension class to be able to pass information about the
# debugging environment from the c-extension to the user.
#
# pkg:gem/byebug#lib/byebug/core.rb:113
class Exception
  # pkg:gem/byebug#lib/byebug/core.rb:114
  def __bb_context; end
end

# Adds a `byebug` method to the Kernel module.
#
# Dropping a `byebug` call anywhere in your code, you get a debug prompt.
#
# pkg:gem/byebug#lib/byebug/attacher.rb:34
module Kernel
  # pkg:gem/byebug#lib/byebug/attacher.rb:35
  def byebug; end

  # pkg:gem/byebug#lib/byebug/attacher.rb:47
  def debugger; end

  # pkg:gem/byebug#lib/byebug/attacher.rb:41
  def remote_byebug(host = T.unsafe(nil), port = T.unsafe(nil)); end
end
