# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `prettier` gem.
# Please instead update this file by running `bin/tapioca gem prettier`.


# pkg:gem/prettier#lib/prettier.rb:6
module Prettier
  class << self
    # pkg:gem/prettier#lib/prettier.rb:14
    def run(args); end
  end
end

# pkg:gem/prettier#lib/prettier.rb:11
Prettier::BINARY = T.let(T.unsafe(nil), String)

# pkg:gem/prettier#lib/prettier.rb:10
Prettier::PLUGIN = T.let(T.unsafe(nil), String)

# pkg:gem/prettier#lib/prettier.rb:12
Prettier::VERSION = T.let(T.unsafe(nil), String)
