# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pry-byebug` gem.
# Please instead update this file by running `bin/tapioca gem pry-byebug`.


# pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:5
module Byebug
  extend ::Byebug::Helpers::ReflectionHelper

  private

  def add_catchpoint(_arg0); end
  def breakpoints; end
  def catchpoints; end
  def contexts; end
  def current_context; end
  def debug_load(*_arg0); end
  def lock; end
  def post_mortem=(_arg0); end
  def post_mortem?; end
  def raised_exception; end
  def start; end
  def started?; end
  def stop; end
  def stoppable?; end
  def thread_context(_arg0); end
  def tracing=(_arg0); end
  def tracing?; end
  def unlock; end
  def verbose=(_arg0); end
  def verbose?; end

  class << self
    def add_catchpoint(_arg0); end
    def breakpoints; end
    def catchpoints; end
    def contexts; end
    def current_context; end
    def debug_load(*_arg0); end
    def lock; end
    def post_mortem=(_arg0); end
    def post_mortem?; end
    def raised_exception; end
    def start; end
    def started?; end
    def stop; end
    def stoppable?; end
    def thread_context(_arg0); end
    def tracing=(_arg0); end
    def tracing?; end
    def unlock; end
    def verbose=(_arg0); end
    def verbose?; end
  end
end

# Extends raw byebug's processor.
#
# pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:9
class Byebug::PryProcessor < ::Byebug::CommandProcessor
  # Called when a breakpoint is hit. Note that `at_line`` is called
  # inmediately after with the context's `stop_reason == :breakpoint`, so we
  # must not resume the pry instance here
  #
  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:80
  def at_breakpoint(breakpoint); end

  # Called when the debugger wants to stop at a regular line
  #
  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:64
  def at_line; end

  # Called when the debugger wants to stop right before a method return
  #
  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:71
  def at_return(_return_value); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:14
  def bold(*args, **_arg1, &block); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:13
  def output(*args, **_arg1, &block); end

  # Set up a number of navigational commands to be performed by Byebug.
  #
  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:45
  def perform(action, options = T.unsafe(nil)); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:10
  def pry; end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:10
  def pry=(_arg0); end

  # Wrap a Pry REPL to catch navigational commands and act on them.
  #
  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:26
  def run(&_block); end

  private

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:93
  def n_hits(breakpoint); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:114
  def perform_backtrace(_options); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:142
  def perform_down(options); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:130
  def perform_finish(*_arg0); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:150
  def perform_frame(options); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:120
  def perform_next(options); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:125
  def perform_step(options); end

  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:134
  def perform_up(options); end

  # Resume an existing Pry REPL at the paused point.
  #
  # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:102
  def resume_pry; end

  class << self
    # pkg:gem/pry-byebug#lib/byebug/processors/pry_processor.rb:16
    def start; end
  end
end

# pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:3
class Pry
  extend ::Forwardable
end

# pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:4
module Pry::Byebug; end

# Wrapper for Byebug.breakpoints that respects our Processor and has better
# failure behavior. Acts as an Enumerable.
#
# pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:9
module Pry::Byebug::Breakpoints
  extend ::Enumerable
  extend ::Pry::Byebug::Breakpoints

  # Adds a file breakpoint.
  #
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:63
  def add_file(file, line, expression = T.unsafe(nil)); end

  # Adds a method breakpoint.
  #
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:51
  def add_method(method, expression = T.unsafe(nil)); end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:44
  def breakpoints; end

  # Changes the conditional expression for a breakpoint.
  #
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:78
  def change(id, expression = T.unsafe(nil)); end

  # Deletes an existing breakpoint with the given ID.
  #
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:89
  def delete(id); end

  # Deletes all breakpoints.
  #
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:100
  def delete_all; end

  # Disables a breakpoint with the given ID.
  #
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:115
  def disable(id); end

  # Disables all breakpoints.
  #
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:122
  def disable_all; end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:136
  def each(&block); end

  # Enables a disabled breakpoint with the given ID.
  #
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:108
  def enable(id); end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:144
  def find_by_id(id); end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:140
  def last; end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:132
  def size; end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:128
  def to_a; end

  private

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:153
  def change_status(id, enabled = T.unsafe(nil)); end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:159
  def validate_expression(exp); end
end

# Breakpoint in a file:line location
#
# pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:16
class Pry::Byebug::Breakpoints::FileBreakpoint < ::SimpleDelegator
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:17
  def source_code; end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:21
  def to_s; end
end

# Breakpoint in a Class#method location
#
# pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:29
class Pry::Byebug::Breakpoints::MethodBreakpoint < ::SimpleDelegator
  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:30
  def initialize(byebug_bp, method); end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:35
  def source_code; end

  # pkg:gem/pry-byebug#lib/pry/byebug/breakpoints.rb:39
  def to_s; end
end

class Pry::REPL
  extend ::Forwardable

  class << self
    # pkg:gem/pry-byebug#lib/pry-byebug/pry_ext.rb:19
    def start(options = T.unsafe(nil)); end

    # pkg:gem/pry-byebug#lib/pry-byebug/pry_ext.rb:8
    def start_with_pry_byebug(options = T.unsafe(nil)); end

    # pkg:gem/pry-byebug#lib/pry-byebug/pry_ext.rb:6
    def start_without_pry_byebug(options); end
  end
end

# Main container module for Pry-Byebug functionality
#
#
# Main container module for Pry-Byebug functionality
#
# pkg:gem/pry-byebug#lib/pry-byebug/helpers/location.rb:3
module PryByebug
  # Reference to currently running pry-remote server. Used by the processor.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/base.rb:10
  def current_remote_server; end

  # Reference to currently running pry-remote server. Used by the processor.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/base.rb:10
  def current_remote_server=(_arg0); end

  private

  # Ensures that a command is executed in a local file context.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/base.rb:25
  def check_file_context(target, msg = T.unsafe(nil)); end

  # Checks that a target binding is in a local file context.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/base.rb:17
  def file_context?(target); end

  class << self
    # Ensures that a command is executed in a local file context.
    #
    # pkg:gem/pry-byebug#lib/pry-byebug/base.rb:25
    def check_file_context(target, msg = T.unsafe(nil)); end

    # Checks that a target binding is in a local file context.
    #
    # pkg:gem/pry-byebug#lib/pry-byebug/base.rb:17
    def file_context?(target); end
  end
end

# Display the current stack
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/backtrace.rb:9
class PryByebug::BacktraceCommand < ::Pry::ClassCommand
  include ::PryByebug::Helpers::Navigation

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/backtrace.rb:23
  def process; end
end

# Add, show and remove breakpoints
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:12
class PryByebug::BreakCommand < ::Pry::ClassCommand
  include ::PryByebug::Helpers::Breakpoints
  include ::PryByebug::Helpers::Location
  include ::PryByebug::Helpers::Multiline

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:50
  def options(opt); end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:62
  def process; end

  private

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:111
  def add_breakpoint(place, condition); end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:93
  def new_breakpoint; end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:102
  def option_to_method(option); end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:106
  def print_all; end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:88
  def process_condition; end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:78
  def process_delete; end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:78
  def process_delete_all; end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:78
  def process_disable; end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:78
  def process_disable_all; end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:78
  def process_enable; end

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/breakpoint.rb:84
  def process_show; end
end

# Continue program execution until the next breakpoint
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/continue.rb:11
class PryByebug::ContinueCommand < ::Pry::ClassCommand
  include ::PryByebug::Helpers::Navigation
  include ::PryByebug::Helpers::Breakpoints
  include ::PryByebug::Helpers::Location

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/continue.rb:31
  def process; end
end

# Travel down the frame stack
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/down.rb:9
class PryByebug::DownCommand < ::Pry::ClassCommand
  include ::PryByebug::Helpers::Navigation

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/down.rb:27
  def process; end
end

# Exit pry REPL with Byebug.stop
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/exit_all.rb:9
class PryByebug::ExitAllCommand < ::Pry::Command::ExitAll
  # pkg:gem/pry-byebug#lib/pry-byebug/commands/exit_all.rb:10
  def process; end
end

# Run until the end of current frame
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/finish.rb:9
class PryByebug::FinishCommand < ::Pry::ClassCommand
  include ::PryByebug::Helpers::Navigation

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/finish.rb:20
  def process; end
end

# Move to a specific frame in the callstack
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/frame.rb:9
class PryByebug::FrameCommand < ::Pry::ClassCommand
  include ::PryByebug::Helpers::Navigation

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/frame.rb:27
  def process; end
end

# pkg:gem/pry-byebug#lib/pry-byebug/helpers/location.rb:4
module PryByebug::Helpers; end

# Common helpers for breakpoint related commands
#
# pkg:gem/pry-byebug#lib/pry-byebug/helpers/breakpoints.rb:10
module PryByebug::Helpers::Breakpoints
  # Prints a message with bold font.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/helpers/breakpoints.rb:21
  def bold_puts(msg); end

  # Byebug's array of breakpoints.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/helpers/breakpoints.rb:14
  def breakpoints; end

  # Max width of breakpoints id column
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/helpers/breakpoints.rb:77
  def max_width; end

  # Prints a header for the breakpoint list.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/helpers/breakpoints.rb:63
  def print_breakpoints_header; end

  # Print out full information about a breakpoint.
  #
  # Includes surrounding code at that point.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/helpers/breakpoints.rb:30
  def print_full_breakpoint(breakpoint); end

  # Print out concise information about a breakpoint.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/helpers/breakpoints.rb:52
  def print_short_breakpoint(breakpoint); end
end

# Compatibility helper to handle source location
#
# pkg:gem/pry-byebug#lib/pry-byebug/helpers/location.rb:8
module PryByebug::Helpers::Location
  private

  # Current file in the target binding. Used as the default breakpoint
  # location.
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/helpers/location.rb:15
  def current_file(source = T.unsafe(nil)); end

  class << self
    # Current file in the target binding. Used as the default breakpoint
    # location.
    #
    # pkg:gem/pry-byebug#lib/pry-byebug/helpers/location.rb:15
    def current_file(source = T.unsafe(nil)); end
  end
end

# Helpers to help handling multiline inputs
#
# pkg:gem/pry-byebug#lib/pry-byebug/helpers/multiline.rb:8
module PryByebug::Helpers::Multiline
  # Returns true if we are in a multiline context and, as a side effect,
  # updates the partial evaluation string with the current input.
  #
  # Returns false otherwise
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/helpers/multiline.rb:15
  def check_multiline_context; end
end

# Helpers to aid breaking out of the REPL loop
#
# pkg:gem/pry-byebug#lib/pry-byebug/helpers/navigation.rb:8
module PryByebug::Helpers::Navigation
  # Breaks out of the REPL loop and signals tracer
  #
  # pkg:gem/pry-byebug#lib/pry-byebug/helpers/navigation.rb:12
  def breakout_navigation(action, options = T.unsafe(nil)); end
end

# Run a number of lines and then stop again
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/next.rb:10
class PryByebug::NextCommand < ::Pry::ClassCommand
  include ::PryByebug::Helpers::Navigation
  include ::PryByebug::Helpers::Multiline

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/next.rb:29
  def process; end
end

# Run a number of Ruby statements and then stop again
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/step.rb:9
class PryByebug::StepCommand < ::Pry::ClassCommand
  include ::PryByebug::Helpers::Navigation

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/step.rb:26
  def process; end
end

# Travel up the frame stack
#
# pkg:gem/pry-byebug#lib/pry-byebug/commands/up.rb:9
class PryByebug::UpCommand < ::Pry::ClassCommand
  include ::PryByebug::Helpers::Navigation

  # pkg:gem/pry-byebug#lib/pry-byebug/commands/up.rb:27
  def process; end
end
