# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec_in_context` gem.
# Please instead update this file by running `bin/tapioca gem rspec_in_context`.


# RSpec
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/context_management.rb:15
module RSpec
  class << self
    # Allows you to define contexts outside of RSpec.describe blocks
    #
    # @param name [String, Symbol] Name of the defined context
    # @param namespace [String, Symbol] Namespace where to store your context
    # @param ns Alias of namespace
    # @param silent [Boolean] Does the in_context should wrap itself into a context block with its name
    # @param print_context [Boolean] Reverse alias of silent
    # @param block [Proc] code that will be injected later
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context.rb:31
    def define_context(name, namespace: T.unsafe(nil), ns: T.unsafe(nil), silent: T.unsafe(nil), print_context: T.unsafe(nil), &_arg5); end
  end
end

# Core
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/context_management.rb:17
module RSpec::Core; end

# ExampleGroup
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/context_management.rb:19
class RSpec::Core::ExampleGroup
  extend ::RspecInContext::ContextManagement
end

class RSpec::Core::Formatters::DocumentationFormatter < ::RSpec::Core::Formatters::BaseTextFormatter
  include ::RspecInContext::Formatters::DocumentationFormatterPatch
end

# Main wrapping module
# Base module
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/version.rb:1
module RspecInContext
  include ::RspecInContext::InContext

  mixes_in_class_methods ::RspecInContext::InContext::ClassMethods

  class << self
    # @api private
    # Inclusion convenience of the gem in RSpec
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context.rb:16
    def included(base); end
  end
end

# Error type when multiple namespaces contain a context with the same name
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:20
class RspecInContext::AmbiguousContextName < ::RspecInContext::Error; end

# Context struct
# @attr [Proc] block what will be executed in the test context
# @attr [Class] owner current rspec context class. This will be used to know where a define_context has been defined
# @attr [String | Symbol] name represent the name by which the context can be found.
# @attr [String | Symbol] namespace namespace for context names to avoid collisions
# @attr [Boolean] silent does the in_context wrap itself into a context with its name or an anonymous context
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
class RspecInContext::Context < ::Struct
  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def block; end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def block=(_); end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def name; end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def name=(_); end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def namespace; end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def namespace=(_); end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def owner; end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def owner=(_); end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def silent; end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
  def silent=(_); end

  class << self
    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
    def [](*_arg0); end

    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
    def inspect; end

    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
    def keyword_init?; end

    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
    def members; end

    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:29
    def new(*_arg0); end
  end
end

# Allow context to be scoped inside a block
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/context_management.rb:3
module RspecInContext::ContextManagement
  # @api private
  # prepending a RSpec method so we can know when a describe/context block finish
  # its reading
  #
  # pkg:gem/rspec_in_context#lib/rspec_in_context/context_management.rb:7
  def subclass(parent, description, args, registration_collection, &_arg4); end
end

# Base error class for all gem errors
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:4
class RspecInContext::Error < ::StandardError; end

# pkg:gem/rspec_in_context#lib/rspec_in_context/formatters/documentation_formatter_patch.rb:4
module RspecInContext::Formatters; end

# Prepended onto RSpec::Core::Formatters::DocumentationFormatter to
# hide the anonymous context wrappers that silent in_context creates.
#
# Without this patch, each silent in_context adds a blank line and an
# extra indentation level to --format documentation output.
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/formatters/documentation_formatter_patch.rb:10
module RspecInContext::Formatters::DocumentationFormatterPatch
  # pkg:gem/rspec_in_context#lib/rspec_in_context/formatters/documentation_formatter_patch.rb:25
  def example_group_finished(notification); end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/formatters/documentation_formatter_patch.rb:11
  def example_group_started(notification); end
end

# Main module containing almost every methods
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:32
module RspecInContext::InContext
  mixes_in_class_methods ::RspecInContext::InContext::ClassMethods

  class << self
    # Meta method to add a new context
    # @api private
    #
    # @note Will warn if a context is overridden
    # @raise [InvalidContextName] if context_name is nil or empty
    # @raise [MissingDefinitionBlock] if no block is provided
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:67
    def add_context(context_name, owner = T.unsafe(nil), namespace = T.unsafe(nil), silent = T.unsafe(nil), &block); end

    # Remove all stored contexts (both scoped and global).
    # Useful for memory cleanup in long-running test suites with
    # dynamically generated contexts.
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:57
    def clear_all_contexts!; end

    # Contexts container + creation
    # Keys are normalized to strings so symbols and strings are interchangeable.
    # @api private
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:48
    def contexts; end

    # Find a context.
    # @api private
    # @raise [NoContextFound] if no context is found
    # @raise [AmbiguousContextName] if multiple namespaces contain the same context name
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:101
    def find_context(context_name, namespace = T.unsafe(nil)); end

    # Look into every namespace to find the context
    # Uses dig to avoid auto-vivifying empty namespace entries
    # @api private
    # @raise [AmbiguousContextName] if multiple namespaces contain the same context name
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:117
    def find_context_across_all_namespaces(name_key); end

    # Hook for easier inclusion of the gem in RSpec
    # @api private
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:41
    def included(base); end

    # @api private
    # Define a context from outside a RSpec.describe block
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:143
    def outside_define_context(context_name, namespace, silent, &_arg3); end

    # @api private
    # Delete a context
    #
    # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:133
    def remove_context(current_class); end
  end
end

# This module define the methods that will be available for the end user inside RSpec tests
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:149
module RspecInContext::InContext::ClassMethods
  # Let you define a context that can be reused later
  #
  # @param context_name [String, Symbol] The name of the context that will be re-used later
  # @param namespace [String, Symbol] namespace name where the context will be stored.
  #   It helps reducing collisions when you define "global" contexts
  # @param ns [String, Symbol] Alias of namespace
  # @param block [Proc] Contain the code that will be injected with #in_context later
  # @param silent [Boolean] Does the in_context wrap itself into a context with its name or an anonymous context
  # @param print_context [Boolean] Reverse alias of silent
  #
  # @note contexts are scoped to the block they are defined in.
  #
  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:207
  def define_context(context_name, namespace: T.unsafe(nil), ns: T.unsafe(nil), silent: T.unsafe(nil), print_context: T.unsafe(nil), &_arg5); end

  # Used in context definition
  # Place where you want to re-inject code passed in argument of in_context
  # (for more examples look at tests)
  #
  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:180
  def execute_tests; end

  # Use a context and inject its content at this place in the code
  #
  # @param [String, Symbol] context_name The context namespace
  # @param [*Any] args Any arg to be passed down to the injected context
  # @param [String, Symbol] namespace namespace name where to look for the context
  # @param [String, Symbol] ns Alias for :namespace
  # @param block Content that will be re-injected (see #execute_tests)
  #
  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:157
  def in_context(context_name, *args, namespace: T.unsafe(nil), ns: T.unsafe(nil), &block); end

  # @deprecated Use {#instantiate_context} or {#execute_tests} instead
  #
  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:187
  def instanciate_context; end

  # pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:184
  def instantiate_context; end
end

# Name of the Global context
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:34
RspecInContext::InContext::GLOBAL_CONTEXT = T.let(T.unsafe(nil), Symbol)

# Error type when context_name is nil or empty
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:16
class RspecInContext::InvalidContextName < ::ArgumentError; end

# Error type when define_context is called without a block
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:12
class RspecInContext::MissingDefinitionBlock < ::ArgumentError; end

# Error type when no context is found from its name (and eventually namespace)
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/in_context.rb:8
class RspecInContext::NoContextFound < ::RspecInContext::Error; end

# Version of the gem
#
# pkg:gem/rspec_in_context#lib/rspec_in_context/version.rb:3
RspecInContext::VERSION = T.let(T.unsafe(nil), String)
