# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-faker` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-faker`.


# pkg:gem/rubocop-faker#lib/rubocop/faker.rb:3
module RuboCop; end

# pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:4
module RuboCop::Cop; end

# pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:5
module RuboCop::Cop::Faker; end

# Checks that Faker arguments style is based on Faker 2.
# Use keyword arguments instead of positional arguments.
#
# @example
#   # bad
#   Avatar.image(slug, size, format)
#
#   # good
#   Avatar.image(slug: slug, size: size, format: format)
#
# pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:16
class RuboCop::Cop::Faker::DeprecatedArguments < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:48
  def on_csend(node); end

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:25
  def on_send(node); end

  private

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:73
  def add_offense_for_arguments(node, argument, message); end

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:118
  def argument_keywords; end

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:109
  def arguments_range(node); end

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:82
  def autocorrect(corrector, node); end

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:91
  def build_kwargs_style(node, keywords); end

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:101
  def faker_class_name(node); end

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:56
  def format_message(keyword:, arg:, index:, class_name:, method_name:); end

  # pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:52
  def unique_generator_method?(node); end
end

# pkg:gem/rubocop-faker#lib/rubocop/cop/faker/deprecated_arguments.rb:20
RuboCop::Cop::Faker::DeprecatedArguments::MSG = T.let(T.unsafe(nil), String)

# RuboCop Faker project namespace.
#
# pkg:gem/rubocop-faker#lib/rubocop/faker.rb:5
module RuboCop::Faker; end

# A plugin that integrates RuboCop Faker with RuboCop's plugin system.
#
# pkg:gem/rubocop-faker#lib/rubocop/faker/plugin.rb:8
class RuboCop::Faker::Plugin < ::LintRoller::Plugin
  # pkg:gem/rubocop-faker#lib/rubocop/faker/plugin.rb:9
  def about; end

  # pkg:gem/rubocop-faker#lib/rubocop/faker/plugin.rb:22
  def rules(_context); end

  # pkg:gem/rubocop-faker#lib/rubocop/faker/plugin.rb:18
  def supported?(context); end
end

# pkg:gem/rubocop-faker#lib/rubocop/faker/version.rb:5
RuboCop::Faker::VERSION = T.let(T.unsafe(nil), String)
