name: Tests

on:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        ruby: ['3.3', '3.4', '4.0']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
      - name: Run type checking (Sorbet)
        run: bundle exec srb tc
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Check formatting (Syntax Tree)
        run: bundle exec stree check './lib/**/*.rb' './spec/**/*.rb' Guardfile Rakefile './*.gemspec' Gemfile
